### ISSUE TITLE
Background Kit

### ISSUE THREAD

**Issue by kre8sions** [powerhome/playbook#1001]
![Background](https://user-images.githubusercontent.com/9784112/90511776-001d8780-e12b-11ea-9abb-502ff3efd35e.jpg)

This kit acts as a standard container. It should accept children/blocks.

div tag by default
can take a **tag prop.**

Use image kit to create background images. (**image_url prop**)

It should have a  **color prop**: to change background color of the container
_using only defined backgrounds from playbook_
https://playbook.powerapp.cloud/utilities

**Stretch Goal**
Utilize lazy loading for image backgrounds

https://github.com/aFarkas/lazysizes#js-api---events

**Comment by jasoncypret** [comment]
@kre8sions I think we need some examples for them to build to display this. Also, we should add white as a background color I think

**Comment by jasoncypret** [comment]
Linked here: https://nitro.powerhrg.com/runway/backlog_items/NUX-1402

**Comment by jasoncypret** [comment]
Shipped!
