### ISSUE TITLE
Collapsible Kit [NUXE-8]

### ISSUE THREAD

**Issue by kre8sions** [powerhome/playbook#1003]
<img width="444" alt="Screen Shot 2020-08-17 at 2 30 41 PM" src="https://user-images.githubusercontent.com/9784112/90431012-5f7d8800-e096-11ea-818e-ebb642dcc90a.png">
<img width="451" alt="Screen Shot 2020-08-17 at 2 30 20 PM" src="https://user-images.githubusercontent.com/9784112/90431017-63110f00-e096-11ea-8307-2a7bc7265560.png">

**REACT ONLY**
This kit should take 2 blocks.
- a block for the trigger area
- a block for content area

See link here -> https://github.com/powerhome/nitro-storybook/blob/master/components/CollapsibleCard/CollapsibleCard.jsx

Icon should switch from up and down based on open and closed state and icon is automatically added to the trigger area

This kit should utilize sub components in react see Card examples here -> https://playbook.powerapp.cloud/kits/card/react

Should have simple transition animation

**Stretch Goal **
create a vanilla JS rails kit

**Comment by jasoncypret** [comment]
Backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-8
