### ISSUE TITLE
Selectable Card - Image Example

### ISSUE THREAD

**Issue by kre8sions** [powerhome/playbook#1004]
##### Kit Background & Use Cases
This is not a new kit, but rather additions to selectable card kit. **This requires that #997 be built first.**
We want to be able to select an image thumbnail. This could be used as a gallery feature in the future where the user taps on a thumbnail and gets a larger image to preview. Another use case would be selecting images in the collection layout for tag addition and deletion (used in hometour).
 
##### Screens & Design References
<img width="798" alt="Screen Shot 2020-08-17 at 9 53 04 AM" src="https://user-images.githubusercontent.com/9784112/90403857-8f656500-e06f-11ea-96bd-d4541519dca7.png">

##### Kit Specifications 
No new props needed. You will be adding an example doc to show the image kit inside the selectable card kit. You should use several examples from [unsplash api](https://unsplash.com/developers). Use the single select option of the kit and don't show indicators. See how card kit is implemented padding to its inner children as an example. This behaves like a radio button.

- Utilize Selectable Card, Image kits
- Url prop:  for image
- Size should be the "sm" version
- Padding: removed so image can go full width

**Comment by jasoncypret** [comment]
@kre8sions As this is built the cards would be whatever size the image kit allows correct?

**Comment by kre8sions** [comment]
@jasoncypret yes the card should take the form of the image

**Comment by jasoncypret** [comment]
Shipped!
