### ISSUE TITLE
NitroSearch Playbook Filter

### ISSUE THREAD

**Issue by roxannecojocariu** [powerhome/playbook#1030]
**Describe the bug**
There appears to be an issue with the kit and it can be recreated in the [Corporate Directory](https://nitro.powerhrg.com/directory).  The old NitroSearch had a caching method that would store old filters so you could navigate away and back and see the old search results, but we don't believe that is true with this kit (especially since we can recreate this in the Corporate Directory).

**To Reproduce**
1. Go to 'https://nitro.powerhrg.com/directory'
2. Click on the filter icon and filter by anything EXCEPT User and click "apply".
3. Navigate to any other Nitro link and then navigate, a second time, to the Corporate Directory.
4. You will see the filter _appears_ to still show, but if you click to sort in any order, the page refreshes and the search filter "resets", displaying unfiltered results.
5. We noticed the params are not persisted on the second page navigation. We are unsure if this needs to be an update to the kit or to the nitro search wrapping of the kit.

**Screenshots**
Even better, here's a video: https://s3-hq-f5.powerhrg.com/nitro-production/apm/blobs/data/000/026/063/original/Number_9.mp4?AWSAccessKeyId=IWSW00NEQHMEYQTLZ7E9&Signature=otJDHvbnRQr1HZnteUluYn0BDls%3D&Expires=3196724954

**Comment by thestephenmarshall** [comment]
I can reproduce this one. An interesting point to make here is that is seems that filter sorting has some parameters missing. 

Example:

https://nitro.powerhrg.com/projects?q%5Bcreated_at_beginning_of_day_gteq%5D=08%2F02%2F2020&q%5Bcreated_at_end_of_day_lteq%5D=08%2F25%2F2020&q%5Bcurrent_state_in%5D%5B%5D=&q%5Bitems_product_id_in%5D%5B%5D=&q%5Blead_user_id_eq%5D=&q%5Bproject_number_start%5D=&q%5Bs%5D=lead_set_for+asc&q%5Bterritory_id_eq%5D=1&utf8=%E2%9C%93

and then from this view, I sorted by `Date` ala:

https://nitro.powerhrg.com/projects?utf8=%E2%9C%93&q%5Bcreated_at_beginning_of_day_gteq%5D=08%2F02%2F2020&q%5Bcreated_at_beginning_of_day_gteq%5D=08%2F02%2F2020&q%5Bcreated_at_end_of_day_lteq%5D=08%2F25%2F2020&q%5Bcreated_at_end_of_day_lteq%5D=08%2F25%2F2020&q%5Bproject_number_start%5D=&q%5Bcurrent_state_in%5D%5B%5D=&q%5Bitems_product_id_in%5D%5B%5D=&q%5Bterritory_id_eq%5D=&q%5Blead_user_id_eq%5D=&q%5Bs%5D%5B%5D=created_at+DESC

So it appears that we will need to dig in to correcting the sorting links to ensure that existing filters are not lost. To prove this, we follow these steps:

1. go here https://nitro.powerhrg.com/directory
2. choose `User Experience Engineer` for `Title` which yields [this url](https://nitro.powerhrg.com/directory?utf8=%E2%9C%93&q%5Bfull_name_cont%5D=&q%5Buser_title_id_eq%5D=907&q%5Bterritory_id_eq%5D=&q%5Bdepartment_id_eq%5D=&letter=)
3. Go away to https://nitro.powerhrg.com
4. Go back to https://nitro.powerhrg.com/directory and note the filter is still applied
5. Hover over the sort link of choice and notice that [it is missing the additional query parameters required to filter](https://nitro.powerhrg.com/directory?q%5Bs%5D=last_name+desc)
6. Open the filters click "Apply" again
7. Click on a sort link and see that [the link contains the proper query params for filters](https://nitro.powerhrg.com/directory?letter=&q%5Bdepartment_id_eq%5D=&q%5Bfull_name_cont%5D=&q%5Bs%5D=last_name+desc&q%5Bterritory_id_eq%5D=&q%5Buser_title_id_eq%5D=907&utf8=%E2%9C%93)

**Comment by thestephenmarshall** [comment]
@roxannecojocariu this is a Nitro bug 100%. Give the two links in my example above a try. Same behavior.

**Comment by roxannecojocariu** [comment]
Per Stephen's comment above and further investigation, we confirmed this is a Nitro issue and are closing this ticket/issue.
