### ISSUE TITLE
Filter Kit Random Scrollbar (Windows OS issue)

### ISSUE THREAD

**Issue by roxannecojocariu** [powerhome/playbook#1032]
**Describe the bug**
Random scrollbar in the Filter kit on Windows OS in a Firefox browser.  Adam Liss discovered this.

**To Reproduce**
1. With a Windows OS in Firefox, navigate to [coporate directory](https://nitro.powerhrg.com/directory)
2. Observe random scrollbar.

**Expected behavior**
No random scrollbar in Filter.

**Screenshots**
![Random_Scroll_Bar](https://user-images.githubusercontent.com/35009869/91215292-4dc56180-e6e2-11ea-9736-01f5c820588d.png)

**Comment by thestephenmarshall** [comment]
@roxannecojocariu can he reproduce this on any other page that is using Playbook filters?

**Comment by roxannecojocariu** [comment]
> @roxannecojocariu can he reproduce this on any other page that is using Playbook filters?

@thestephenmarshall yes, he looked at the Corporate Directory.

**Comment by roxannecojocariu** [comment]
I didn't mean to close this. Oopz.

**Comment by jasoncypret** [comment]
@thestephenmarshall Were you able to replicate in any other supported browser?

**Comment by jasoncypret** [comment]
Linked for investigation: https://nitro.powerhrg.com/runway/backlog_items/NUX-1379

**Comment by jasoncypret** [comment]
Going to attempt a fix, but we won't know if it works.
