### ISSUE TITLE
Filter Kit - Menu Visible for split second on page load

### ISSUE THREAD

**Issue by roxannecojocariu** [powerhome/playbook#1033]
**Describe the bug**
Every time I load the Corporate Directory page, it quickly flashes the `sorting` drop down. Video attached.  This can also be directly reproduced on the [kit itself](https://playbook.powerapp.cloud/kits/filter)

**To Reproduce**
1. Go to [the corporate directory](https://nitro.powerhrg.com/directory) or [the playbook filter kit])https://playbook.powerapp.cloud/kits/filter)
2. Pay close attention to the Sorting section (right side of filter) and note how the menu appears for a split second on page load.

**Expected behavior**
The menu should not be open upon page load.

**Screenshots**
Even better, a video: [FilterMenuOpen.mov.zip](https://github.com/powerhome/playbook/files/5125786/FilterMenuOpen.mov.zip)

**Comment by thestephenmarshall** [comment]
[This might be the problem area](https://github.com/powerhome/playbook/blob/v6.4.0/app/pb_kits/playbook/pb_popover/index.js#L11-L13) as it is moving the popover container to the inner `<body>` element as a direct child for z index support. Could be that we need to investigate timing and perhaps even apply some sort of hide effect initially to prevent this flashing.

**Comment by jasoncypret** [comment]
Linked: https://nitro.powerhrg.com/runway/backlog_items/NUX-1381

**Comment by jasoncypret** [comment]
Merged into release
