### ISSUE TITLE
Tooltip kit displays arrow wrong when direction is bottom

### ISSUE THREAD

**Issue by haydenrou** [powerhome/playbook#1046]
**Describe the bug**
When selecting "bottom" for the direction of the tooltip, it displays the arrow down instead of up to where it's being hovered over.

**Expected behavior**
I'd expect the arrow to point up, however if I'm off the mark here please let me know.

**Screenshots**
<img width="117" alt="Screenshot 2020-08-27 at 2 30 25 PM" src="https://user-images.githubusercontent.com/21108297/91496949-075f3680-e88b-11ea-8752-2f212fba8f93.png">

**Desktop (please complete the following information):**
Chrome

**Code**
```
            <%= pb_rails("body", props: { text: email_campaign.status, margin_right: "xs", margin_bottom: "xs", id: "campaign_status_tooltip" }) %>

            <%= pb_rails("tooltip", props: {
              trigger_element_id: "campaign_status_tooltip",
              tooltip_id: "tooltip-2",
              position: "bottom",
              dark: true,
            }) do %>
              <%= email_campaign.failed_reason %>
            <% end %>

```

**Comment by jasoncypret** [comment]
Linked: https://nitro.powerhrg.com/runway/backlog_items/NUX-1382

**Comment by jasoncypret** [comment]
Merged
