### ISSUE TITLE
FA SVG Icons are Slow When Loaded > 150 in a View

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#1056]
**Describe the bug**

Installation Scheduler view is using approx 200-300 SVG icons via the IconCircle kit. The SVG handler is seemingly very slow to render. 

Hints: @stephenagreer mentioned the 450MB~ RAM heap as well as potentially seeing SVGs loaded large then sized down which may lead to a solution.

**To Reproduce**
1. Go checkout Playgrounds branch and implement loop for 300 SVG icons
2. Run JS profiler and record memory and CPU consumption

**Expected behavior**
Performance should be snappy. SVG should be loaded in a reasonable size.

**Screenshots**

<img width="2032" alt="Screen Shot 2020-09-01 at 11 42 32 AM" src="https://user-images.githubusercontent.com/2293844/91882189-3a694780-ec48-11ea-80d3-d1a5ad6e5754.png">

**Additional context**
None

**Comment by jasoncypret** [comment]
Added to backlog https://nitro.powerhrg.com/runway/backlog_items/NUXE-36
