### ISSUE TITLE
Date Picker Kit Form Label

### ISSUE THREAD

**Issue by terryfinn** [powerhome/playbook#1116]
**Describe the bug**
The date picker kit does not create a label.

**To Reproduce**
1. Create a form kit with a date picker input
1. The label text for the input will display but is not a label

**Expected behavior**
The data picker kit integrates into the the form system like the other inputs and associate a label for the input, and the label should be generated and default based on the name of the input using the generation strategy rails uses.

**Screenshots**
<img width="1075" alt="Screen Shot 2020-09-28 at 9 14 11 PM" src="https://user-images.githubusercontent.com/584017/94501330-92f01e00-01cf-11eb-90e3-7ca59ba1d903.png">

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**
None

**Comment by bh247484** [comment]
You can pass a string value to the label prop if you need a custom label, i.e. `props: { label: 'My Custom Label' }`.  Are there situations in which you'd need it to be a `<label />` instead of a div?

**Comment by bh247484** [comment]
Just took a closer look at this.  This bit escaped me yesterday: 

"the label should be generated and default based on the name of the input using the generation strategy rails uses"

I can dynamically parse the `:name` in the form helper and pass that as a label prop to the date picker.  Only concern there is that it'd look strange for Ransack queries or other forms where the name is useful to the developer but meaningless to the end user.  Even if I created logic to prune Ransack predicates and convert snake case text there would almost certainly be edge cases.

Seems safer to have the developer pass the string they'd like to appear in as a label prop.
