### ISSUE TITLE
Date Picker Kit Form Value attribute

### ISSUE THREAD

**Issue by terryfinn** [powerhome/playbook#1117]
**Describe the bug**
The date picker kit form does not have a value attribute.

**To Reproduce**
1. Create a form with a model using the form kit and date picker input
1. The value of the date picker will display the current date and not the value of the attribute for the model

**Expected behavior**
When a form has a model, and the model has a value for the date picker attribute, that value should display in the form.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**
None

**Comment by jasoncypret** [comment]
Changed the labels since this was working as intended. This is a new feature request
