### ISSUE TITLE
Date picker constraint validaiton

### ISSUE THREAD

**Issue by terryfinn** [powerhome/playbook#1118]
**Describe the bug**
The date picker does not display constraint validation errors.

**To Reproduce**
1. Use the date picker kit in a form with a constraint validation, like being required.
2. Violate the constraint validation
3. Not see the constraint validation violation

**Expected behavior**
When a input has a constraint validation error we should see it reported.

**Screenshots**
<img width="1787" alt="Screen Shot 2020-09-28 at 9 47 37 PM" src="https://user-images.githubusercontent.com/584017/94503342-3e02d680-01d4-11eb-8295-99ab8bec170b.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox Developer Edition
 - Version 82.0b1 (64-bit)

**Smartphone (please complete the following information):**
Not Tested

**Additional context**
I think this is an issue do the the input for the date picker having the readonly attribute set.

**Comment by bh247484** [comment]
Fix for this on the way.  You're absolutely right about the readonly.  Shame that it breaks form validation but I've created a workaround.  Won't require additional legwork for the user/developer.  You'll still only have to pass `required: true` as a prop.
