### ISSUE TITLE
Appointment Result

### ISSUE THREAD

**Issue by markiearnold** [powerhome/playbook#112]
Design Details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard41

This kit should use icon circle, label value, and avatar

![image](https://user-images.githubusercontent.com/863031/64572988-25a4ed00-d32f-11e9-82dd-4b19abd1165a.png)

**Comment by jasoncypret** [comment]
@kre8sions Another one

**Comment by jasoncypret** [comment]
Closing till we rename
