### ISSUE TITLE
Prevent Badge Kit breaking into two lines

### ISSUE THREAD

**Issue by christinaatai** [powerhome/playbook#1133]
**Describe the bug**

The Badge Kit breaks into two lines when the table column (or container/div) width is less than the width of the badge.

**To Reproduce**

This can be reproduced when table columns are shorter than the badge width.

**Expected behavior**

I expect the badge to stay in one line

**Screenshots**

<img width="408" alt="Screen Shot 2020-10-02 at 12 48 53 PM" src="https://user-images.githubusercontent.com/42459486/94948651-a5a77300-04ad-11eb-96a4-20d73c9393cc.png">

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**
 
n/a

**Additional context**

This can be easily fixed with adding `nowrap` class to the overarching div.

**Comment by jasoncypret** [comment]
Closing...working on this sprint
