### ISSUE TITLE
Get Section Separator Kit to work on dark mode

### ISSUE THREAD

**Issue by christinaatai** [powerhome/playbook#1134]
**Describe the bug**

Dark version is not working for Section Separator Kit; dark class is not being applied.

**To Reproduce*

Have section separator on a dark background.

**Expected behavior**

In dark mode, border color should be $border-dark, caption color should be dark, and card color should be dark.

**Screenshots**

What it currently looks like:
<img width="742" alt="screen-shot-2020-10-01-at-4-30-48-pm" src="https://user-images.githubusercontent.com/42459486/94948987-3716e500-04ae-11eb-9c1a-1749c26d6753.png">

What it should look like:
<img width="561" alt="Screen Shot 2020-10-02 at 12 53 31 PM" src="https://user-images.githubusercontent.com/42459486/94949044-4ac24b80-04ae-11eb-9482-9812e4f18abb.png">

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

**Additional context**

**Comment by jasoncypret** [comment]
Added here: https://nitro.powerhrg.com/runway/backlog_items/NUXE-166
