### ISSUE TITLE
DatePicker kit default_date prop displays incorrect date for today

### ISSUE THREAD

**Issue by derricklannaman** [powerhome/playbook#1167]
**Describe the bug**

Using `default_date: (Date.today).httpdate` will display the date as yesterday. Also occurs for `min_date` property. 

**To Reproduce**

1. Change default_date or min_date to (Date.today).httpdate, its renders the previous day
2. For min_date, it allows previous day

**Expected behavior**
`default_date: (Date.today).httpdate` should display today's date

**Screenshots**
![Screen Shot 2020-10-22 at 11 21 53 AM](https://user-images.githubusercontent.com/615262/96908064-bec69280-1461-11eb-9fd1-4c5d83e05e6a.png)

<img width="437" alt="Screen Shot 2020-10-22 at 11 21 07 AM" src="https://user-images.githubusercontent.com/615262/96908134-d56ce980-1461-11eb-884d-92204400ab63.png">

![Screen Shot 2020-10-22 at 11 22 49 AM](https://user-images.githubusercontent.com/615262/96908234-f2092180-1461-11eb-8c07-bd918b4a7a70.png)

**Desktop (please complete the following information):**
 - Browser [e.g. FF]
 - Version [e.g. 81.0.2]

**Additional context**
Using default_date: Date.today.to_s(:date_picker) displays the correct day

**Comment by bh247484** [comment]
### The Problem
The Javascript Date object constructor parses strings in an odd way.  The weird behavior above is an example.  In short using strings to convert date objects between Ruby and Javascripts gets messy in a hurry.

### The Symptoms
If you invoke `Date.today` in Ruby (on Dec 11th, 10:50a EST) and then use the `.httpdate` method to convert it to a string you'll end up with this... 
<img width="264" alt="ruby_no_time" src="https://user-images.githubusercontent.com/57693937/101926872-c53fd380-3ba1-11eb-9934-e219e423e8ee.png">
Notice the timezone is zero-ed out, `00:00:00 GMT`.

If you then pass that exact string above into a Javascript date constructor like so... 
<img width="438" alt="js_yesterday" src="https://user-images.githubusercontent.com/57693937/101925874-63329e80-3ba0-11eb-9347-465424eb2bec.png">
...you'll end up with yesterdays date.  Very strange.

It has something to do with how the constructor tries to parse and make sense of the timezone, and then how your local machine interprets the result relative to its own timezone.

### The Solution
Here's a way to preserve the timezone info along with the date upon string conversion.
<img width="265" alt="ruby_time" src="https://user-images.githubusercontent.com/57693937/101926434-287d3600-3ba1-11eb-960a-b90857e6df69.png">

Then pass that into the Javascript Date constructor...
<img width="445" alt="js_today_2" src="https://user-images.githubusercontent.com/57693937/101926701-8873dc80-3ba1-11eb-80e2-f4643e216d7f.png">

...and we get what we're looking for, today's date.

### The Takeaways

1. I'll update Playbook docs for the date picker to use `Time.current.httpdate`.  I myself didn't know about this behavior (js date to string conversion) when I was building the kit.  The docs are a misleading/wrong.
2. If you're trying to pass Ruby date objects to the Date Picker, or indeed any date string to any JS Date constructor, make sure the string you're passing has (accurate) timezone info included or Javascript will make a wild (probably wrong) guess about how to convert it.

**Comment by derricklannaman** [comment]
@bh247484 💯

**Comment by bh247484** [comment]
Going to leave issue open until I fix the docs.
