### ISSUE TITLE
Nav Items in New Browser Tabs

### ISSUE THREAD

**Issue by garettarrowood** [powerhome/playbook#1212]
**Is your feature request related to a problem? Please describe.**

We are using the Nav Kit and need some of the nav items to open up in a new tab.

**Describe the solution you'd like**

A new Nav Item prop, that can default to the current window (as it stands now), or be passed a value to open the link in a new tab, e.g. `target="_blank"`.

**What we had to do to get around this in Nitro**

```erb
<a href="<%= our_path(object) %>" target="_blank">
  <%= pb_rails("nav/item", props: { icon_left: "chart-bar", text: "Download Results" }) %>
</a>

<%= pb_rails("section_separator") %>
```

**Comment by jasoncypret** [comment]
Added to the backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-324

**Comment by jasoncypret** [comment]
Shipped
