### ISSUE TITLE
Tooltip Rails kit: Tooltip arrow is not centered

### ISSUE THREAD

**Issue by stevelandwehr** [powerhome/playbook#1222]
**Describe the bug**
On the top and bottom-positioned Tooltip Rails kit, the arrow is not centered to the tooltip; the arrow appears to be about 10 pixels off to the left.

**To Reproduce**
This is the code being used for the Tooltip kit where the arrow appears to be off-center:

`<%= pb_rails("tooltip", props: {
  trigger_element_id: "result-#{object_id}-sample-email-link",
  tooltip_id: "sample-email-tooltip-result-#{object_id}",
  position: "top",
  dark: true
}) do %>
  Send Sample Email
<% end %>`

**Expected behavior**
The arrow is expected to be centered to the tooltip.

**Screenshots**
![image](https://user-images.githubusercontent.com/151394/100135588-b5ed2600-2e3e-11eb-8005-390b4b2aed61.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser Firefox
 - Version 83.0

**Comment by jasoncypret** [comment]
The story has been added to an upcoming sprint 
https://nitro.powerhrg.com/runway/backlog_items/NUXE-313
