### ISSUE TITLE
Typeahead w/ Pills Kit: Passing the selected pills as form parameters in a Rails Form

### ISSUE THREAD

**Issue by derricklannaman** [powerhome/playbook#1228]
**Is your feature request related to a problem? Please describe.**

Currently, If you have a rails form and want to use the `Typeahead with Pills`, and want to pass the selected 'pills' through the form as params, you'll have to `hidden_field_tags` and attach those selected elements to those tags. 

**Describe the solution you'd like**

Similar to single selection `form.typeahead` below....
```ruby
  <%= form.typeahead :example_user, props: { data: { typeahead_example1: true, user: {} }, placeholder: "Search for a user" } %>
```
Perhaps....
```ruby
<%= form.typeahead, props: { id: "typeahead-pills-example1", default_options: [options.first], options: options, label: "Colors", name: :foo, pills: true }) %>
```
with the form passing the pills and not needing `hidden_field_tag`s

**Comment by thestephenmarshall** [comment]
Thanks for opening this @derricklannaman. Could you provide a mock-up example of what you are describing?

Here is the basic example for Typeahead w/ Pills:

```rb
<%= pb_rails("typeahead", props: { id: "typeahead-pills-example1", default_options: [options.first], options: options, label: "Colors", name: :foo, pills: true }) %>
```

Currently, we are using hidden fields because any other form input would be visible within the UI. Could you explain the problem you are wanting to solve?

**Comment by thestephenmarshall** [comment]
Bump @derricklannaman. Any thoughts?

**Comment by jasoncypret** [comment]
Closed not enough detail
