### ISSUE TITLE
React Filter Form buttons are too close together

### ISSUE THREAD

**Issue by kellyeryan** [powerhome/playbook#1232]
**Describe the solution you'd like**
I would like the filter form buttons to have padding between them so that they do not overlap or look like they are too close together.

**Describe alternatives you've considered**
I can put a specific width on the filter form and this will separate the buttons, but this problem keeps coming up as feedback and I continue to have to change the width in each story. It seems like it would be better just to change it on the kit level.

**Additional context**

Just to clarify the issue, here is a screenshot:

<img width="783" alt="Screen Shot 2020-12-04 at 9 30 23 AM" src="https://user-images.githubusercontent.com/51907753/101175607-5dbedc80-3613-11eb-9048-bb94cd89e81d.png">

**Comment by jasoncypret** [comment]
The popover automatically sizes to your content. We could add new props to possibly pass a min-width to the popover. We will need to review this a bit more to see what options could be added to make this easier.

There are two ways to solve your problem. I suggest using the spacing props to add a margin to your buttons `margin_left="xs"`. The second solution would be to add a min-width to your form. `style="min-width: 350px;"`.

**Comment by jasoncypret** [comment]
Added to backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-348
