### ISSUE TITLE
TypeAhead kit not recognizing getOptionLabel and getOptionValue props

### ISSUE THREAD

**Issue by KatherineMuedas** [powerhome/playbook#1242]
**Describe the bug**
When implementing react TypeAhead we will often need to customize the `label and value` to be `name and id`. React select has a prop `getOptionLabel` and `getOptionValue` that we could use for this matter but it seems that these two props are not working on playbook TypeAhead. The customization of label and value is something that we will need quite often so it would be great if we could find a way to make `getOptionLabel` and `getOptionValue` props useable with playbook. I've been playing around with playbook code to see why those props are not working but no luck yet. Right now we have a workaround on the Nitro side but it is not ideal. 
Thank you!
```
/* @flow */

import React from 'react'
import { Typeahead } from '../..'

const options = [
  { name: 'Windows', id: '#FFA500' },
  { name: 'Siding', id: '#FF0000' },
  { name: 'Doors', id: '#00FF00' },
  { name: 'Roofs', id: '#0000FF' },
]

const TypeaheadExample = () => {
  return (
    <>
      <Typeahead
          isMulti
          label="Example"
          getOptionLabel={(option) => option.name}
          getOptionValue={(option) => option.id}
          options={options}
          placeholder=""
      />
    </>
  )
}

export default TypeaheadExample
```

<img width="1291" alt="Screen Shot 2020-12-09 at 10 57 33 AM" src="https://user-images.githubusercontent.com/6829115/101653511-6184a180-3a0d-11eb-9f6f-cbb853a22d60.png">

**Expected behavior**
Being able to pass `getOptionLabel` and `getOptionValue` to TypeAhead kit
https://medium.com/@lahiru0561/react-select-with-custom-label-and-custom-search-122bfe06b6d7

**Comment by KatherineMuedas** [comment]
@gmfvpereira @rodolfoasantos

**Comment by thestephenmarshall** [comment]
Thanks for opening this ticket. The [Runway ticket](https://nitro.powerhrg.com/runway/backlog_items/NUXE-342) to track this work has been created.

**Comment by thestephenmarshall** [comment]
Technically, this isn't a bug, but rather an enhancement. As with any kit, once we discover new requirements, any necessary props will be added to support those. The original requirements did not include `getOptionLabel` or `getOptionValue` as the use case was not initially present. Note: this will not affect the expediency of this ticket.

**Comment by gmfvpereira** [comment]
@thestephenmarshall do you know why this is not working? Since you're spreading the kit props to the react-select, I was expecting it to work out of the box...

**Comment by gmfvpereira** [comment]
Nvm, I saw the PR already.
