### ISSUE TITLE
Tooltip Rails kit: degraded page performance when a lot of tooltip kits are on the page

### ISSUE THREAD

**Issue by stevelandwehr** [powerhome/playbook#1245]
**Describe the bug**
The Email Templates index page (`/email/email_templates`) has over 130 templates displaying on the page. When tooltip kits are added to each template's "send" and "edit" icons, this page starts to have some degraded performance such as UI elements disappearing and the page becoming slow when vertically scrolling the page.

_NOTE:_ In the master branch, the tooltip kits have been removed from the Email Templates index page. [Here is the commit that added the tooltip kits to the Email Templates index page](https://github.com/powerhome/nitro-web/commit/71cd91bbd503af33e887ada760316910fb944052#diff-11c9d0d0ec66a5e5366cdda0e23607bf5021f2d39fcf04fc84e648e4ffeb099f)

**To Reproduce**
1. With tooltips added to the page, go to the Email Templates index page: `/email/email_templates`
2. Vertically scroll the page
3. UI elements disappear and the page becomes slow

**Expected behavior**
When a page has a lot of tooltip kits, UI elements don't disappear and the page doesn't become slow when it's scrolled.

**Screenshots**
Email Templates index page _with_ tooltip kits: https://cloud.powerhrg.com/s/R2ADWmrtjgFJ2eZ

Email Templates index page _without_ tooltip kits: https://cloud.powerhrg.com/s/d9M2G2kbZTAaiA6

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Firefox
 - Version: 83.0

**Smartphone (please complete the following information):**

**Additional context**
https://nitro.powerhrg.com/runway/backlog_items/BOP-764

**Comment by thestephenmarshall** [comment]
Investigating this. Initially, this makes me wonder if we are not re-using the Popover kit and instead generating `n` Popovers (one for each row). This would indeed be counter-productive and fixing it will require JS to be written for the given view in order to ensure the initial instance of Popover can be re-used, ultimately conserving memory and enhancing overall UI performance.

**Comment by thestephenmarshall** [comment]
@powerhome/birds-of-prey Can I get some more details on what the `tooltip` content was? Was it static? Is there a WIP branch that I can pull down?

**Comment by stevelandwehr** [comment]
> @powerhome/birds-of-prey Can I get some more details on what the `tooltip` content was? Was it static? Is there a WIP branch that I can pull down?

One of the tooltip's content was "Send Sample Email" and another tooltip's content was "Edit Email Template". Both were static. There is not a WIP branch, but [here is the commit that added them](https://github.com/powerhome/nitro-web/commit/71cd91bbd503af33e887ada760316910fb944052#diff-11c9d0d0ec66a5e5366cdda0e23607bf5021f2d39fcf04fc84e648e4ffeb099f).

**Comment by web-kat** [comment]
@thestephenmarshall [here is a link to the PR where we removed the tooltips](https://github.com/powerhome/nitro-web/pull/18266/files).

**Comment by thestephenmarshall** [comment]
thanks @powerhome/birds-of-prey

**Comment by jasoncypret** [comment]
https://nitro.powerhrg.com/runway/backlog_items/NUXE-350
