### ISSUE TITLE
Charts are not completely compatible with Flex kit on mobile

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#1248]
**Describe the bug**

When nesting any Chart kit (which uses Highcharts) inside of the `Flex` kit, unexpected chart widths are realized. The chart will typically overflow the Flex container instead of obeying the "width" of the container.

**To Reproduce**
1. Create a view which uses `Flex` and optionally `FlexItem` 
2. Add the `Gauge` kit to the `FlexItem` as a child
3. resize the view to mobile
4. notice the overflowing `Gauge` kit 

**Expected behavior**

The chart kits' widths should be contained within the `Flex` kit computed width.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: All
 - Browser All supported browsers
 - Version [latest]

**Smartphone (please complete the following information):**
 - Device: All
 - OS: Android and iOS
 - Browser Chrome and FF
 - Version [latest]

**Additional context**

Investigate the possibility of flexbox attributes to remedy the situation. This will require some research, trial and error to determine the feasibility. Currently, the only known workaround is to avoid nesting chart kit instances in `Flex` kit.

**Comment by jasoncypret** [comment]
Self-reported things should just go on our backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-349
