### ISSUE TITLE
DatePicker: Ability to clear date field easier 

### ISSUE THREAD

**Issue by derricklannaman** [powerhome/playbook#1250]
Using the date picker, there was a suggestion regarding not being able to clear the Date Picker field...
> "Not sure if there is a way to do this, but there isn't an "intuitive way" to clear the date.  There's not an "X" or anything next to it.  Instead you have to click into it and hit backspace to clear it. You can always hit clear, but if you have multiple filters and only want to remove the date, not the most user friendly option"

**Describe the solution you'd like**
![Screen Shot 2020-12-10 at 3 09 58 PM](https://user-images.githubusercontent.com/615262/101830247-d7663700-3af9-11eb-97b7-a26ecdb3296a.png)
Image above from Flatpickr docs: https://flatpickr.js.org/examples/#flatpickr-external-elements

#### Additional context from the conversation:
Kevin Schlabach:

> Eva, the Solar search form date picker has a "today", "Clear" and "Close" set of buttons 
> at the bottom (see attached)...  but this doesn't look to be in the latest kit in Playbook. 
> Was this intentional?
> 
> I'd suggest opening an issue on the kit in Playbook for the 3 options from the prior version to be 
added to this one and we ship as is.

Eva Louderback:

> The reason that date picker was used for the Solar search form was because the Playbook date picker 
> wasn't built yet. I would open an issue for those options to be added
> 

#### Thanks and Awesome work! 💯

**Comment by jasoncypret** [comment]
@bh247484 This will require a story for design. Can you add 2 stories to Runway? The first story being to expose a clear method the developers can call (similar to the onChange & onClose hooks). This story would allow Derrick to achieve his mock without too much fuss. The second story would be a design story to explore "clear date" options within the popover.

**Comment by bh247484** [comment]
@derricklannaman For a near term, hook-style solution you can get ahold of the flapickr instance with javascript and then call `.clear()` on it (probably from within some DOM element's eventListener).

```
const fpInstance = document.querySelector('#pickerId')._flatpickr
fpInstance.clear()
```
Where `pickerId` is the string you passed to the `picker_id` (rails) or `pickerId` (react) prop.

Meanwhile we'll work on design and implementation for 'today', 'clear', and 'close' buttons.

**Comment by jasoncypret** [comment]
https://nitro.powerhrg.com/runway/backlog_items/NUXE-352
https://nitro.powerhrg.com/runway/backlog_items/NUXE-354
