### ISSUE TITLE
Typeahead - Add support for custom options

### ISSUE THREAD

**Issue by rodolfoasantos** [powerhome/playbook#1252]
Hi!

Legion is working on some features for Learning Dojo and we got a block due to a limitation of the Typeahead Kit.

Usually, at Nitro, we want to use Typehead components to render results like:

![Screen Shot 2020-12-14 at 11 30 59](https://user-images.githubusercontent.com/754389/102096013-f9fe9580-3e02-11eb-8a1b-3b67fa74a800.png)

At the Playbook's typeahead, looks like it makes use of the User kit, but limited to render the Avatar and the name (Missing the territory and role title).

[Typeahead Option](https://github.com/powerhome/playbook/blob/master/playbook/app/pb_kits/playbook/pb_typeahead/components/Option.jsx#L20-L25)
```javascript
  return (
    <components.Option {...props}>
      <div>
        <Choose>
          <When condition={imageUrl}>
            <User
                align="left"
                avatarUrl={imageUrl}
                name={props.label}
                orientation="horizontal"
            />
          </When>
          <When condition={!imageUrl}>
            {props.label}
          </When>
        </Choose>
      </div>
    </components.Option>
  )
```

We would like to request a way to render a custom result in a generic way. Having control over what we want to render, means making the Playbook Typeahead kit even more flexible.

For example:
I want to render the User kit as results of my Typeahead setup:

```javascript
  <Typeahead
       async
       isMulti
       label="Github Users"
       loadOptions={promiseOptions}
       onChange={handleOnChange}
       onMultiValueClick={handleOnMultiValueClick}
       placeholder="type the user name"
       optionRenderer={(props) => (
            <User
                avatarUrl={props.user.imageUrl}
                name={props.user.label}
                title={props.user.title}
                territory={props.user.territory}
            />
           )
        }
  />
```

Thank you!

**Comment by jasoncypret** [comment]
Added  to the backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-356

**Comment by thestephenmarshall** [comment]
The first thing this kit needs is JS test coverage before we go in to adding custom options support. I do not think we have an official GH issue for that, but instead rather an internal RW ticket in the backlog.

**Comment by jasoncypret** [comment]
@rodolfoasantos How this one going? Need any support?

**Comment by rodolfoasantos** [comment]
@jasoncypret Hey, @KatherineMuedas is working on that. Everything is doing good so far. Thanks for asking.

**Comment by jasoncypret** [comment]
This shipped!
