### ISSUE TITLE
More spacing between stacked Typeahead form pills [NUXE-376]

### ISSUE THREAD

**Issue by kellyeryan** [powerhome/playbook#1263]
**Is your feature request related to a problem? Please describe.**

I would like the Typeahead form pills to have more spacing when they are stacked. The kit as is doesn't allow the developer to put padding or margin around the pills.

<img width="655" alt="more_spacing_bt_pills" src="https://user-images.githubusercontent.com/51907753/102272214-699d7f00-3eee-11eb-9a25-0b1dd1e1db66.png">

**Comment by christinaatai** [comment]
Runway ticket: https://nitro.powerhrg.com/runway/backlog_items/NUXE-376

**Comment by jasoncypret** [comment]
Merged
