### ISSUE TITLE
Add ability to adjust alignment of Popover [NUXE-385]

### ISSUE THREAD

**Issue by kellyeryan** [powerhome/playbook#1264]
**Is your feature request related to a problem? Please describe.**
I would like the ability to adjust where the popover is placed so that it is clearer what is being edited.

I was asked to align the popover with the popover reference (the circle icon button) as follows:

<img width="799" alt="Screen Shot 2020-12-15 at 4 01 07 PM" src="https://user-images.githubusercontent.com/51907753/102272701-2b548f80-3eef-11eb-9298-93e731d1b96c.png">

As it stands now, there are 4 different ways to place the popover, top, bottom, left, right. Here is what it looks like when the popover is set to "bottom." There is no way to move it in any direction to make it clearer which button has been pressed.

<img width="1571" alt="Screen Shot 2020-12-15 at 4 00 06 PM" src="https://user-images.githubusercontent.com/51907753/102272830-60f97880-3eef-11eb-8f62-369077753d3a.png">

**Describe alternatives you've considered**

I have tried adding special styling to the popover but I can't seem to affect the `pb_popover_body` class that could be used to move it to the right.

This seems like it is the same issue that occurs in the Filter kit, where the popover always makes itself flush with the left side of the browser and is not able to be adjusted.

**Comment by jasoncypret** [comment]
@thestephenmarshall Not sure how feasible this one is. Can we use poppers offset for this? Last I tried it offset didn't work the way I expected. Can you weigh in?

**Comment by thestephenmarshall** [comment]
This can be achieved, but will require update to the `Popover` kit. The docs on Popper.js (the underlying lib handling positioning) states how offset works here https://popper.js.org/docs/v2/modifiers/offset

[In this part of index.js](https://github.com/powerhome/playbook/blob/master/playbook/app/pb_kits/playbook/pb_popover/index.js#L103), we would need to make another `data-popover-offset` attribute that could be accepted and override this logic when provided.

**Comment by jasoncypret** [comment]
@kellyeryan This shipped and is in production. Thanks for the suggestion!
