### ISSUE TITLE
Inconsistent Font Weight comparing TextInput to TextArea

### ISSUE THREAD

**Issue by garettarrowood** [powerhome/playbook#1280]
**Describe the bug**

Textarea inputs do not show up with the same font weight as a text input.

Here is textarea with text from the website:

<img width="705" alt="Screen Shot 2020-12-22 at 1 53 23 PM" src="https://user-images.githubusercontent.com/12770108/102923217-601b9600-445d-11eb-8aba-2daf616ae8f4.png">

And here is text input:

<img width="525" alt="Screen Shot 2020-12-22 at 1 53 48 PM" src="https://user-images.githubusercontent.com/12770108/102923236-67db3a80-445d-11eb-94f8-0aaaf164362b.png">

**Expected behavior**

These appear the same. Based on talking with Christina, the text input bold seems to be the correct font weight.

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser: Chrome

**Additional context**

Custom CSS fixes this issue, but it'd be nice not to need it.

**Comment by jasoncypret** [comment]
@garettarrowood this change was made on purpose. We need to keep textarea non bold. It's usually displayed back to the user in raw body like text.

We can look at potentially changing the weight of inputs...but we need to look at that as a design system review.

I'm adding this to the review topics.
