### ISSUE TITLE
Auto Resizing TextInput/TextArea [NUXE-384]

### ISSUE THREAD

**Issue by garettarrowood** [powerhome/playbook#1281]
**Is your feature request related to a problem? Please describe.**

All text inputs in Nitro Survey need to auto-resize as the user enters more text. We are accomplishing this by leveraging `"react-autosize-textarea"`.

At the time of writing, Playbook's `TextArea` kit adds a scroll bar (cutting off the top lines).
At the time of writing, Playbook's `TextInput` kit scrolls to the right (cutting off the text at the start of the input).

**Describe the solution you'd like**

Either change the default behavior of both of these kits to auto-resize.

### OR

Be able to pass a prop to these that allow the inputs to auto-resize.

**Describe alternatives you've considered**

We are using `"react-autosize-textarea"` and wrapping it in the Playbook `TextArea`, but we still are needing to apply extra styling to get it looking right.

**Additional context**

In the image below, the top input is a textarea using `"react-autosize-textarea"`. The bottom is a `TextInput` that scrolls to the right as we enter more text.

<img width="892" alt="screen-shot-2020-12-22-at-1-40-20-pm" src="https://user-images.githubusercontent.com/12770108/102924071-d8cf2200-445e-11eb-9890-b6b14eb22cb7.png">

**Comment by jasoncypret** [comment]
I've never seen auto-resize added to a text input. They are fundamentally different in functions. We are considering adding to a text area, but not text inputs. I've seen resizing on text inputs horizontally...but not vertically. That said I have auto sizing textareas on our backlog. https://nitro.powerhrg.com/runway/backlog_items/NUXE-384

**Comment by jasoncypret** [comment]
Merged
