### ISSUE TITLE
Alt replaces monogram on broken avatar links [NUXE-381]

### ISSUE THREAD

**Issue by kellyeryan** [powerhome/playbook#1282]
**Describe the bug**
When there is a broken avatar link, the `alt` obscures the monogram for the avatar. This should be fixed so that the monogram shows when there is a broken avatar link.

**To Reproduce**
1. Go to flight control in qa or localhost - https://nitroqa.powerhrg.com/flight_control
2. Add a reviewer to a PR. 
3. See error - the monogram should be visible but also covered with the alt (which is the name of the person).

**Expected behavior**
I would like the monogram (and only the monogram) to be visible when there is a broken avatar link.

**Screenshots**
<img width="1499" alt="Screen Shot 2020-12-22 at 2 15 14 PM" src="https://user-images.githubusercontent.com/51907753/102924791-3b74ed80-4460-11eb-8d19-09aad26c2689.png">
<img width="441" alt="Screen Shot 2020-12-22 at 2 15 21 PM" src="https://user-images.githubusercontent.com/51907753/102924793-3ca61a80-4460-11eb-96fb-9292eb8655eb.png">
<img width="497" alt="Screen Shot 2020-12-22 at 2 15 32 PM" src="https://user-images.githubusercontent.com/51907753/102924794-3d3eb100-4460-11eb-89dd-3d255bbc379f.png">
<img width="303" alt="Screen Shot 2020-12-22 at 2 15 38 PM" src="https://user-images.githubusercontent.com/51907753/102924796-3dd74780-4460-11eb-84cb-679c7483cd11.png">

**Desktop (please complete the following information):**
This bug exists on both firefox and chrome, although it looks a little different on chrome: 

<img width="1465" alt="Screen Shot 2020-12-22 at 2 17 34 PM" src="https://user-images.githubusercontent.com/51907753/102924959-85f66a00-4460-11eb-82ed-b339cf3ba658.png">

Fixing it should fix it in both browsers without any additional code.

**Comment by jasoncypret** [comment]
Runway ticket: https://nitro.powerhrg.com/runway/backlog_items/NUXE-381
