### ISSUE TITLE
Add onClose prop to Filter kit [NUXE-431]

### ISSUE THREAD

**Issue by eabousaif** [powerhome/playbook#1288]
**Is your feature request related to a problem? Please describe.**
A few stories in the NOVA backlog are requesting a Close button on the filter popover to toggle it, as opposed to having to click away from the popover to close it. Currently, it's not feasible to implement a toggler button to close the popover since we don't have a way to add an event listener to the popover button and set the initial state. Also, having that option moving forward would be helpful for other filters.

<img width="426" alt="Screen Shot 2020-12-30 at 10 14 16 AM" src="https://user-images.githubusercontent.com/46111475/103363007-10098880-4a88-11eb-902d-98d2b1f995a9.png">

**Comment by christinaatai** [comment]
A standard would need to be explored for the filter kit popover. The design exploration and standardization of this will be tackled in [NUX-1635](https://nitro.powerhrg.com/runway/backlog_items/NUX-1635).

**Comment by jasoncypret** [comment]
I'd like to reference Eva's design here. This should be an option for filter kit...we can enforce standards in Nitro if we want to have it on by default

**Comment by jasoncypret** [comment]
Added to backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-431

**Comment by thestephenmarshall** [comment]
@eabousaif this is already possible in Nitro. See this: https://github.com/powerhome/nitro-web/commit/bb2ead3361a85f9192acfb58096aab02ea5dd73a

**Comment by thestephenmarshall** [comment]
Uploading Screen Recording 2021-04-19 at 12.06.44 PM.mov…
