### ISSUE TITLE
Add ability to specify specific colors to sections of bars in Distribution Kit [NUXE-415]

### ISSUE THREAD

**Issue by idanzonshein** [powerhome/playbook#1293]
**Is your feature request related to a problem? Please describe.**
![Screen Shot 2021-01-06 at 8 04 19 AM](https://user-images.githubusercontent.com/64423490/103771465-ca077400-4ff5-11eb-9f53-20e111aa2299.png)

I am using the distribution kit to show the current status of a review. The mockup specifically showed that each section were to be assigned as green for approved, red for rejected, and grey for pending.

**Describe the solution you'd like**
I want to be able to assign each section that I added into the width array to be a certain color rather than it randomize based on the kits colors order.

**Comment by kevinschlabach** [comment]
**Note:** this is to support [CHPN-112](https://nitro.powerhrg.com/runway/backlog_items/CHPN-112)'s updates in flight control, the current plan is to ship the feature without this update, but hope that these kit updates can catch up quickly

**Comment by jasoncypret** [comment]
Added to sprint: https://nitro.powerhrg.com/runway/backlog_items/NUXE-415
