### ISSUE TITLE
Have the Distribution Bar fully close when section has value of 0 [NUXE-414]

### ISSUE THREAD

**Issue by idanzonshein** [powerhome/playbook#1294]
**Is your feature request related to a problem? Please describe.**
When using the Distribution bar, not always will each section have a value over 0. When a section does have a value of 0, the bar does not fully close and will just show part of the section.

![Screen Shot 2021-01-06 at 8 42 18 AM](https://user-images.githubusercontent.com/64423490/103774916-510b1b00-4ffb-11eb-846c-98fcbbaa2902.png)

**Describe the solution you'd like**
Since the order of colors needs to stay the same, i need the sections to be able to handle a value of 0 and not cut off the bar so that it can fully close and have rounded edges.

**Comment by kevinschlabach** [comment]
**Note:** this is to support [CHPN-112](https://nitro.powerhrg.com/runway/backlog_items/CHPN-112)'s updates in flight control, the current plan is to ship the feature without this update, but hope that these kit updates can catch up quickly

**Comment by jasoncypret** [comment]
Added to sprint https://nitro.powerhrg.com/runway/backlog_items/NUXE-414
