### ISSUE TITLE
Add name prop to Rails Rich Text Editor kit [NUXE-448]

### ISSUE THREAD

**Issue by stevelandwehr** [powerhome/playbook#1299]
**Is your feature request related to a problem? Please describe.**
The Rails Rich Text Editor kit is being used for discussion comments in Runway ([PR](https://github.com/powerhome/nitro-web/pull/18597)). The kit renders a hidden input field but the hidden input doesn't have a `name` attribute to allow the value of the Trix editor to be passed in the form params. 

**Describe the solution you'd like**
It would be helpful to be able to pass a `name` prop to the kit so the prop's value could get set on the hidden input's `name` attribute.

**Describe alternatives you've considered**
[Current work-around](https://github.com/powerhome/nitro-web/pull/18597/files#diff-444d68395b396f5322b4d72bbf07bc3e879e8a9d1ecc54db1862eed89f6fedf5R11) as suggested by Stephen Marshall.

**Comment by jasoncypret** [comment]
Added to the backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-448

**Comment by jasoncypret** [comment]
Merged
