### ISSUE TITLE
Rails Rich Text Editor with focus: true needs 2 clicks to click on something outside the editor

### ISSUE THREAD

**Issue by stevelandwehr** [powerhome/playbook#1301]
**Is your feature request related to a problem? Please describe.**
When using the Rails Rich Text Editor with the `focus` prop set to `true`, in order to click on something else outside of the editor you need to click twice -- one click to lose the focus on the editor, and then a second click to click on the thing you want to click on. The example used here is the discussion comment editor in Runway. After typing my comment, I click on the "Post Comment" button, but that first click makes the editor's toolbar go away and shifts the button up. I then need to click on the button a second time to submit the form.

https://user-images.githubusercontent.com/151394/103934171-68b8d100-50d9-11eb-980c-e81f47517eaf.mov

screen recording also here: https://cloud.powerhrg.com/s/KcDoAGFAefQcxYy

**Describe the solution you'd like**
Clicking outside the editor doesn't need a second click to click on the thing you want to click on.

**Comment by jasoncypret** [comment]
Thanks for sharing @stevelandwehr. Is there somewhere we can see this in action. I can't reproduce. It could be related to the modal, but we won't know for sure without more testing.

**Comment by stevelandwehr** [comment]
> Thanks for sharing @stevelandwehr. Is there somewhere we can see this in action. I can't reproduce. It could be related to the modal, but we won't know for sure without more testing.

Hi @jasoncypret ! We currently don't have this Rich Text Editor being used anywhere with the `focus` prop set to `true`.

**Comment by jasoncypret** [comment]
@stevelandwehr We need a spot to reproduce this bug. If you can open a branch or provide a code pen we can make some progress on it. Otherwise, it will remain stale

**Comment by jasoncypret** [comment]
Closed, not reproducible.
