### ISSUE TITLE
Arrow on Rails Tooltip kit isn't centered [NUXE-453]

### ISSUE THREAD

**Issue by stevelandwehr** [powerhome/playbook#1316]
**Describe the bug**
On the Email Templates index page, each template's row has two Rails Tooltip kits that are in a Flex kit. The "Update Email Template" tooltip's arrow is centered. However, the "Send Sample Email" tooltip's arrow is not centered.

**To Reproduce**
1. Go to /email/email_templates
2. Mouseover the pencil and airplane icons
3. See the misaligned arrow on the "Send Sample Email" tooltip

Here is the PR where the tooltips have been added: https://github.com/powerhome/nitro-web/pull/18714

**Expected behavior**
The tooltip's arrow is centered for all tooltips.

**Screenshots**
https://user-images.githubusercontent.com/151394/104626892-3bc16c80-564b-11eb-9451-ed14bd77017f.mov

![image](https://user-images.githubusercontent.com/151394/104627001-5abffe80-564b-11eb-8bd9-265ea7c437d2.png)

![image](https://user-images.githubusercontent.com/151394/104627045-657a9380-564b-11eb-8a25-21132a2e7561.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Firefox
 - Version: 84.0.2

**Comment by jasoncypret** [comment]
Added to the backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-453

**Comment by kre8sions** [comment]
Bug Fixed #1364
