### ISSUE TITLE
Add data prop to Rich Text Editor [NUXE-447]

### ISSUE THREAD

**Issue by web-kat** [powerhome/playbook#1321]
**Is your feature request related to a problem? Please describe.**
The data `prop` is listed on the Playbook site as available to use with the Rich Text Editor kit, but is not supported.

**Describe the solution you'd like**
The ability to use data attributed with the React and Rails version of the Rich Text Editor kit.

**Comment by jasoncypret** [comment]
Added to the backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-447

**Comment by jasoncypret** [comment]
Merged
