### ISSUE TITLE
Enable FormGroup be entire width of container [NUXE-454]

### ISSUE THREAD

**Issue by kellyeryan** [powerhome/playbook#1335]
**Is your feature request related to a problem? Please describe.**
I was asked by a UX designer to use FormGroup and have the inputs span the full length of the container and I discovered that this was not an option for the FormGroup kit.

**Describe the solution you'd like**
I would like an option to have the FormGroup fields stretch the full width of the container.

**Describe alternatives you've considered**
As far as I can tell, this is not possible with the current implementation of the kit. All my attempts have failed. I have tried width:100%, justify-content-stretch, variations on Flexbox, etc., etc., without success. Even if it could be done with a complex CSS configuration, I think it would be better if the kit just had a `full_width` option. I have decided to use "multi-input-group full" in this [PR](https://github.com/powerhome/nitro-web/pull/18788), so this might be a good place to look for code that allows it to be full width.

**Additional context**

<img width="802" alt="FormGroup_not_full_width" src="https://user-images.githubusercontent.com/51907753/105763321-a7e18180-5f23-11eb-92ac-4cb324a0570d.png">

**Comment by jasoncypret** [comment]
https://nitro.powerhrg.com/runway/backlog_items/NUXE-454
