### ISSUE TITLE
Make React PB check boxes more accessible

### ISSUE THREAD

**Issue by kellyeryan** [powerhome/playbook#1336]
**Is your feature request related to a problem? Please describe.**
As a user with sight-impairment, I would like to be able to tab to and check/uncheck check boxes.

**Describe the solution you'd like**
Ideally, the user would be able to use React PB check boxes using only the keyboard. The user would be able to tab through the options and check/uncheck them using spacebar or enter.

**Describe alternatives you've considered**
We could leave it as is, but it seems like it would be nice to have our pages be accessible to all users. 

**Additional context**
This is fairly easy--I think it is already implemented in the List kit so that could be used as an example. It could just involve making sure there is a `tabIndex="0"` in a `className`. I am implementing this first on the "My Profile" page in the following PR: https://github.com/powerhome/nitro-web/pull/18881

#### Screenshots

Here is what the accessible page should look like using the "Show Tabbing Order" feature in the accessibility section of the firefox browser (found when inspecting the page".

<img width="17" alt="Screen Shot 2021-02-01 at 9 21 40 AM" src="https://user-images.githubusercontent.com/51907753/106470899-0ef4be00-646f-11eb-889f-5a4580c93a8a.png">

**Comment by thestephenmarshall** [comment]
Verified and closing in lieu of https://nitro.powerhrg.com/runway/backlog_items/NUXE-442
