### ISSUE TITLE
Popover doesn't close on any when clicking another popover [NUXE-455]

### ISSUE THREAD

**Issue by haydenrou** [powerhome/playbook#1338]
Speaking to @evalouderback  about using Popover on our story, this came up. We decided making an issue was the best approach, however if this is not playbook domain please let me know.

**Describe the bug**
When selecting `close_on_click: "any"` for the popover [here](https://playbook.powerapp.cloud/kits/popover/rails) , the popover will drop on all scenarios except when clicking another popover. In this case they will both appear open.

**To Reproduce**
1. Go to https://playbook.powerapp.cloud/kits/popover/rails
2. Click on popover
3. Click another popover
4. See both open

**Expected behavior**
The initially selected popover to close

**Comment by jasoncypret** [comment]
Added to the backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-455

**Comment by jasoncypret** [comment]
This shipped awhile ago. We forgot to close
