### ISSUE TITLE
Add id, classname, data to Rails PB Typeahead [NUXE-644]

### ISSUE THREAD

**Issue by kellyeryan** [powerhome/playbook#1360]
**Is your feature request related to a problem? Please describe.**
A bit of a problem--I was working with the Typeahead and I needed to grab information from the input and it was pretty difficult to do. 

**Describe the solution you'd like**
It would be good for this kit (and take very little time!) to add id, classname, and data, so that developers can use the kit more easily.

**Describe alternatives you've considered**
I doubled up on querySelectors this time around and got the input, but it was more complicated than it had to be.

**Screenshot**
<img width="1164" alt="Screen Shot 2021-02-17 at 3 58 41 PM" src="https://user-images.githubusercontent.com/51907753/108267784-a3327680-7139-11eb-8c90-81e8dab884af.png">

**Comment by garettarrowood** [comment]
In this case, I believe adding `input_options` would be the convention. Leaving id/classname/aria/data on the outer element, and allowing any `input_options` to be passed directly to the input.

**Comment by thestephenmarshall** [comment]
Verified as missing. [Runway Story NUXE-644 created](https://nitro.powerhrg.com/runway/backlog_items/NUXE-644).
