### ISSUE TITLE
Passing Methods are not possible with buttons

### ISSUE THREAD

**Issue by kre8sions** [powerhome/playbook#138]
Example:

Like this ->: <%= pb_rails("button", props: { text: "Select", link: "link", method: :post }) %>

**Comment by jasoncypret** [comment]
This is using jquery_ujs

https://www.viget.com/articles/delete-in-rails-without-jquery-and-ujs/

@wadewinningham are we going to support this forever?

**Comment by wadewinningham** [comment]
@jasoncypret I think it will be a while until we can get rid of it. But as of Rails 5.1 (the version we are on) Rails has dropped jquery-ujs support and now has (`rails-ujs`)[https://github.com/rails/rails/tree/master/actionview/app/assets/javascripts] which is therefore preferred.

I have absolutely no idea if we are using a mix of both but if we are, I'd imagine that if there's a place we're using `rails-ujs` sans-jquery, it'd be in the *Runway* code. You may want to confirm with @terryfinn or someone else on @powerhome/birds-of-prey .

**Comment by terryfinn** [comment]
rails-ujs is what runway uses. We do not use jquery-ujs. We only use jquery for modals and select2. For the most part, you don't need to do anything to switch. rails-ujs was mostly an effort to remove the requirement of jquery from rails. None of the jquery features are really required any more for what ujs needs. My understanding is that was why it was removed; vanilla JavaScript APIs in the browser where sufficient. rails-ujs does provide a few helpers beyond what jquery-ujs provided, I think meant as a way of filling the gap of some of the things people use jquery.

We pull it in via [webpacker from the yarn package](https://yarnpkg.com/en/package/rails-ujs). It is a small package, about 4k gzipped.

I am not sure what your trying to do. If you don't want the button to disable while submitting and you don't want the button to ask you to confirm you want to take a action, then you don't need any JavaScript at all, you can just use a form with hidden inputs. This is exactly what [`button_to` provides](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-button_to). But if you want it to submit via ajax, or disable, or confirm before submit, then `ujs` is a good option. For all of those features, switching form jquery-ujs to rails-ujs should be trivial. I don't know if we will use it long term, but ujs is a good and simple way of solving some very common problems that has worked well for me for many years now. I think it would be good to consider using it moving forward.
