### ISSUE TITLE
Multiple Stacked User Kit - no longer fixed size [NUXE-533]

### ISSUE THREAD

**Issue by kevinschlabach** [powerhome/playbook#1390]
**Describe the bug**
I was reviewing the "Multiple User Stacked" kit with @evalouderback and I was confused that the "+4" overlays the avatar so much it's unusable... Eva noted that all 3 of these are supposed to take up the same width, but as of Playbook 8.1.0 they don't anymore.  If anyone is using this in Nitro, it's likely broken... 

**To Reproduce**
Steps to reproduce the behavior: see attached image below from current Playbook screen grab showing 3 variations or visit [playbook kit page](https://playbook.powerapp.cloud/kits/multiple_users_stacked/react)

**Expected behavior**
the 2nd and 3rd examples in Playbook with more than one user listed should consume the same amount of real estate on the screen... this is important because we are planning on swapping out the old square avatars in Runway soon for this kit... but in it's current state, it would be unusable.

**Screenshots**

From current playbook site:
<img width="754" alt="current-kit" src="https://user-images.githubusercontent.com/44237304/110978249-2148fe00-8331-11eb-88c7-f8db3d49bda1.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox 86.0

**Additional context**
This should be treated with priority since it's a regression and it could hold up our transition in an upcoming sprint or two.

**Comment by jasoncypret** [comment]
Yes this one was already in our backlog: https://nitro.powerhrg.com/runway/backlog_items/NUXE-533

**Comment by kevinschlabach** [comment]
Woohoo!
