### ISSUE TITLE
Typeahead Kit - No Options, delayed search results

### ISSUE THREAD

**Issue by kevinschlabach** [powerhome/playbook#1391]
**Describe the bug**

Typeahead React implementations with a search query have started having an issue in recent weeks.  I first saw this on flight control with the 'add reviewers' drop-down.  When clicking into the drop-down, it used to automatically and quickly list all possible users and then reduce as the user typed and the list was updated.  Lately, it initially loads with "no options" and after a short time (sometimes seconds), it will eventually load... or the user can start typing and the results seem to kickstart the process.

At first I thought this was a flight control specific issue, but I'm also seeing this on the [kit page in Playbook](https://playbook.powerapp.cloud/kits/typeahead/react).  The "Github users" example does the same thing.

I don't have enough evidence to point me to other examples in Nitro or Playbook to prove this isn't a code issue in both Playbook and Flight Control... (I am not a developer) so that research should still be pursued.

It's also possible that it was like this all along, but that a spinner was included to inform the user to wait for the query to complete and load the full result list... (I don't remember, I just know it feels different)

In other news, the second example on the page is labelled colors, when it list products.

**To Reproduce**

1. Go to the kit page in Playbook or flight control on a row that doesn't currently have any reviewers
2. click into the field

**Expected behavior**

a list of possible results to select (even without typing ahead to reduce the list)

**Screenshots**

<img width="1116" alt="flight-control" src="https://user-images.githubusercontent.com/44237304/110980426-d7ade280-8333-11eb-9c16-fb683ac14a03.png">

<img width="983" alt="playbook" src="https://user-images.githubusercontent.com/44237304/110980435-d977a600-8333-11eb-92a1-c33a4c0fdd41.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.2
 - Browser: Firefox 86.0

**Additional context**
???

**Comment by jasoncypret** [comment]
Working for me. Perhaps I'm not following. 
![image](https://user-images.githubusercontent.com/863031/110985326-f4e1b180-8331-11eb-8d9c-f1eb29b9fbc3.png)

**Comment by thestephenmarshall** [comment]
@kevinschlabach the data interactivity within this kit is 100% controlled by the implementor of the kit versus the kit source. In the case of Rails, event hooks are provided for the `select`, `remove` and `clear` UI interactions. The population of the data itself as well as the initial data payload provided in the view on load are the responsibility of Flight Control view code including any JavaScript within the Nitro component.

**Comment by kevinschlabach** [comment]
example from flight control:

https://user-images.githubusercontent.com/44237304/110999508-76dfd380-834e-11eb-9e43-aea5d575fa5e.mov

example from playbook kit:

https://user-images.githubusercontent.com/44237304/110999530-8101d200-834e-11eb-90f4-91f0bb60b939.mov

@jasoncypret - I'm guessing it might have to do with query response time?  It happens on arriving to the page, but then starts working after being there for a bit...

Why would it say "no options" when there are options... and shouldn't there be a spinner while it loads instead of default misleading text?

@thestephenmarshall - this is React, not Rails.

**Comment by kevinschlabach** [comment]
@thestephenmarshall - this all makes sense from the technical perspective.  I'm guessing when they updated the page, they referenced the playbook kit page and made it match as the assumed pattern. 

Can I suggest that on the Playbook kit page it says "Search to see options" as this would be better understood by the end user... the phrase 'no options' made me think that nothing would return (but I knew to search to prove that wrong)... then the reference pattern would make more sense even if a team mirrored it blindly.

I will pass this along for the flight control page improvements... Thanks!

**Comment by thestephenmarshall** [comment]
![typeahead-options](https://user-images.githubusercontent.com/2293844/112208443-59c8c180-8be6-11eb-9aa9-a0331b961ab2.gif)

Does this look okay @kevinschlabach ?

**Comment by thestephenmarshall** [comment]
Devs can actually do this now since the prop needed is already available via the library we are using:

```jsx
<Typeahead
  async
  isMulti
  label="Github Users"
  loadingMessage={() => 'Searching for users...'}
  loadOptions={promiseOptions}
  onChange={handleOnChange}
  onMultiValueClick={handleOnMultiValueClick}
  placeholder="Search to see options"
  {...props}
/>
```

For devs: the `loadingMessage` prop is a function that returns the text while the options are loading and the `placeholder` prop replaces the default message you mention with whatever you would like.

**Comment by thestephenmarshall** [comment]
@kevinschlabach I updated the above code example with the prop:

```jsx
noOptionsMessage={() => 'Type to Search'}
```

**Comment by thestephenmarshall** [comment]
[This PR](https://github.com/powerhome/playbook/pull/1407) adds the doc example improvement.

**Comment by kevinschlabach** [comment]
the "add reviewer" search in flight control has been updated to improve this and can be used as a reference for Nitro standards moving forward.
