### ISSUE TITLE
Make playbook rails 6 compatible

### ISSUE THREAD

**Issue by miniyakkos** [powerhome/playbook#1396]
**Is your feature request related to a problem? Please describe.**
Tempo is in the process of upgrading to Rails 6.0.3.5 from 5.2.4.5. We found that playbook has a dependency on `"actionpack", ">= 5.2.4.5", "< 6.0"` which makes it incompatible with Rails 6.

**Describe the solution you'd like**
Change the actionpack dependency to  `">= 5.2.4.5", "< 7.0"`

**Describe alternatives you've considered**
No alternatives

**Additional context**
Running bundle update in Tempo currently errors out with:
```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    nitro_theme was resolved to 0.0.1, which depends on
      playbook_ui (= 7.15.1) was resolved to 7.15.1, which depends on
        actionpack (< 6.0, >= 5.1.6)

    nitro_theme was resolved to 0.0.1, which depends on
      rails (= 6.0.3.5) was resolved to 6.0.3.5, which depends on
        actionpack (= 6.0.3.5)
```

**Comment by thestephenmarshall** [comment]
I think there needs to be some synchronization between this app and the rest of Nitro. Have a look at https://github.com/powerhome/playbook/pull/1393. If we update this version, dependencies in other components will certainly fail to resolve.

**Comment by miniyakkos** [comment]
> I think there needs to be some synchronization between this app and the rest of Nitro. Have a look at #1393. If we update this version, dependencies in other components will certainly fail to resolve.

In that case, can we change it to `">= 5.2.4.4", "< 7.0"`? I'm only suggesting to raise the upper limit to <7.0, so that Tempo is not blocked on the upgrade work. The minimum can stay at 5.2.4.4 for Nitro. actionview and activesupport already have the upper limit at <7.0, I don't see why actionpack can't be the same.

**Comment by thestephenmarshall** [comment]
> Describe the solution you'd like
> Change the actionpack dependency to ">= 5.2.4.5", "< 7.0"

Oh sorry, I read this as you wanting to change the min as well. I think this is definitely doable. @powerhome/ux-team thoughts?
