### ISSUE TITLE
Dark prop for popover kit

### ISSUE THREAD

**Issue by patmccler** [powerhome/playbook#1414]
**Describe the solution you'd like**
The popover kit doesn't react when you pass it `dark` as a prop. 
I think it'd make sense to have the background color of the popover change to a dark background. 
Maybe the shadow could update as well, but that's less clear to me.

**Describe alternatives you've considered**
For now, using the white background popover.

**Additional context**
This came up when implementing the passphrase kit. The kit was designed to use a popover, and a handoff was given to use the passphrase kit on a dark background ([here](https://www.sketch.com/s/09fb700f-4f6c-4c17-821b-dd050706d054/a/nRmEJLa/play))
At Cole's suggestion, I'm sticking with the white background for now and putting this issue in

Here's an example I hacked together to show the difference
<img width="719" alt="Screen Shot 2021-03-31 at 3 22 46 PM" src="https://user-images.githubusercontent.com/28073714/113199309-f87f9e80-9234-11eb-83c7-f2ff2a55ff88.png">
<img width="983" alt="Screen Shot 2021-03-31 at 3 18 49 PM" src="https://user-images.githubusercontent.com/28073714/113199316-fae1f880-9234-11eb-8d7a-b0739207a57f.png">

**Comment by patmccler** [comment]
@coleerikson here's the issue we talked about. Thanks again

**Comment by jasoncypret** [comment]
Great suggestion @patmccler! We have purposely not moved forward with this on the kit. We are still evaluating if we will be adding it or not. Thanks for bringing this up, but plan on using the light popovers for the time being.
