### ISSUE TITLE
Fullwidth buttons don't work with dark mode [NUXE-640]

### ISSUE THREAD

**Issue by patmccler** [powerhome/playbook#1464]
**Describe the bug**
When you use both the fullwidth prop and the dark prop on the button kit, a dark css rule overwrites the fullwidth rule and the button shows up not full width

**To Reproduce**
1. https://playbook.powerapp.cloud/kits/button/react
2. See the fullwidth example - it is full width in light mode view
3. Click the dark toggle
4. See the full width example - it doesn't work in dark

**Expected behavior**
fullWidth: true should work with dark mode

**Screenshots**
<img width="1393" alt="Screen Shot 2021-04-21 at 2 15 17 PM" src="https://user-images.githubusercontent.com/28073714/115601620-06f92d00-a2ac-11eb-961f-8cde8217cb3a.png">
<img width="1389" alt="Screen Shot 2021-04-21 at 2 15 03 PM" src="https://user-images.githubusercontent.com/28073714/115601622-06f92d00-a2ac-11eb-8d63-dda6fe9c1e54.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome/Firefox
 - Version Chrome: 89.0.4389.128, Firefox: 87.0 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
Noticed while using button on a dark screen.

**Comment by jasoncypret** [comment]
This has been added to an upcoming sprint https://nitro.powerhrg.com/runway/backlog_items/NUXE-640
