### ISSUE TITLE
Monospaced typography [NUXE-648]

### ISSUE THREAD

**Issue by garettarrowood** [powerhome/playbook#1475]
**Is your feature request related to a problem? Please describe.**

Project Numbers need to be presented with monospace typography, generally, across the board.

**Describe the solution you'd like**

A prop added to the `body` kit that makes the text yielded to it monospaced. Perhaps `monospace: true`.

**Describe alternatives you've considered**

Not using playbook typography.

**Additional context**

Right now, the Infinity Inc team has a view with this requirement.

**Comment by kre8sions** [comment]
@garettarrowood we created a global prop [numberSpacing] || [number_spacing] it takes the value of tabular and makes numbers monospaced

**Comment by garettarrowood** [comment]
The story attached points at this issue. Is there a PR that you made this change? How does one set a global prop in Playbook? Is there a page on the site that describes this?

**Comment by garettarrowood** [comment]
ah... I think I get it ...

**Comment by kre8sions** [comment]
@garettarrowood https://playbook.powerapp.cloud/visual_guidelines look at number spacing
