### ISSUE TITLE
Dashboard Value kit icons

### ISSUE THREAD

**Issue by eabousaif** [powerhome/playbook#1497]
**Describe the bug**
I'm currently trying to implement a conditional view for the Dashboard Value kit where it's an increase if the number is greater than 0 or a decrease if the number is lower than 0. The CSS for the increase vs decrease colors seems to be working as expected, however, the arrow icon doesn't seem to be matching with the change prop type. 

[Here's the link to the PR handling that](https://github.com/powerhome/nitro-web/pull/20479)

**Screenshots**
![screen-shot-2021-05-17-at-11-54-40-am](https://user-images.githubusercontent.com/46111475/118533617-4897bf00-b716-11eb-9652-afafbf0d48f4.png)

**Comment by thestephenmarshall** [comment]
This bug has to do with this page: https://pr20479.nitro-web.beta.gm.powerapp.cloud/human_resources/people_dashboard?mt=People+Headcount+Dashboard in Nitro. The way it was loading, React was not updating the Dashboard Value kit's contents. 

Dashboard Value kit is not the culprit. 

Closing.
