### ISSUE TITLE
Nitro: Table Styles from Nitro Theme are Overriding Some Table Kit Styles

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#1500]
**Describe the bug**

@stephenmckeon Is working on Sales Books view and has noticed that, even though `responsive="none"` is set on his Table Kit instances, some responsive styles still remain. 

URL: /sales/reps/46508/sales_books (make sure the `Show React Sales Books Ui` feature toggle is enabled on /admin/feature_toggles)

Branch: all-appointments-table

**To Reproduce**
1. Go to '/sales/reps/46508/sales_books'
2. Make the page mobile sized
3. The table should not be responsive, but is responsive 

**Expected behavior**

Setting the prop `responsive="none"` should yield no responsive styles.

**Screenshots**

**Comment by samantharogersphrg** [comment]
Discussed during planning-- while UX will take care of this, it's a problem in Nitro, not Playbook, so we're closing this Issue.
