### ISSUE TITLE
Popover Resizing 

### ISSUE THREAD

**Issue by josephinef9** [powerhome/playbook#1519]
**Describe the bug**
On the react side of the Popover kit, when you use the props `zIndex`, `maxWidth`, and `maxHeight` it changes the spacing inside the popover. 

**To Reproduce**
1. Go to the react popover kit
2. Click on the zIndex or scroll and height settings examples 

**Expected behavior**
The spacing inside the popover when using these two props should be the same as the spacing when not using them.

**Screenshots**
<img width="475" alt="Screen Shot 2021-06-10 at 3 55 32 PM" src="https://user-images.githubusercontent.com/64423298/121588793-5504f400-ca04-11eb-8309-1db05bef00b5.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jasperfurniss** [comment]
@josephinef9 We will take a look at this and have it retain the padding when those props are added.

One quick fix to unblock you, if you are indeed blocked, is to utilize our global spacing props.
I'll post a codesandbox for you shortly, demonstrating that.

**Comment by josephinef9** [comment]
> @josephinef9 We will take a look at this and have it retain the padding when those props are added.
> 
> One quick fix to unblock you, if you are indeed blocked, is to utilize our global spacing props.
> I'll post a codesandbox for you shortly, demonstrating that.

@jasperfurniss thank you so much, that would be really helpful :)

**Comment by samantharogersphrg** [comment]
Tracked in Runway as [NUXE-759](https://nitro.powerhrg.com/runway/backlog_items/NUXE-759).

**Comment by jasperfurniss** [comment]
https://codesandbox.io/s/spring-cherry-il0mc?file=/src/components/App/index.jsx 

Here ya go Jo! @josephinef9 

Does that get you unblocked?
