### ISSUE TITLE
Add ability to upload Pages, Numbers, and Keynote files with the File Upload kit [NUXE-950]

### ISSUE THREAD

**Issue by stevelandwehr** [powerhome/playbook#1575]
**Is your feature request related to a problem? Please describe.**
The [File Upload kit](https://playbook.powerapp.cloud/kits/file_upload/react) doesn't support uploading Pages, Numbers, or Keynote files even though their file types are being passed in the `accept` prop. The file types I've tried passing are:

- application/vnd.apple.keynote
- application/vnd.apple.numbers
- application/vnd.apple.pages
- application/x-iwork-keynote-sffkey
- application/x-iwork-pages-sffpages
- application/x-iwork-numbers-sffnumbers

**Describe the solution you'd like**
I'd like to be able to use the File Upload kit to upload Pages, Numbers, and Keynote files.

**Describe alternatives you've considered**
We've considered, and are currently implementing, using `react-dropzone` to upload files.

**Comment by jasperfurniss** [comment]
@stevelandwehr did you try using the `accept` prop to enable the file types you need?

**Comment by jasoncypret** [comment]
@stevelandwehr sorry, Just now looking at this. Be sure and ping the playbook channel when you add these so we make sure everyone sees them.

**Comment by jasoncypret** [comment]
@stevelandwehr Where are you passing the accepted file type to dropzone?...or are you just accepting all for now? https://github.com/powerhome/nitro-web/pull/21459/files#diff-11faae29eb5bb0ab5c2aa946a424c0742aee91c1a60d4f794f9bcc819738b554R70

**Comment by thestephenmarshall** [comment]
Based on [the source](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L96) the `accept` prop should simply be passed through

**Comment by samantharogersphrg** [comment]
@stevelandwehr Hi Steve! I spoke earlier with Kevin last week and it sounded like this does not block work for BoP; is that correct? I'm going to add this to our backlog in Runway-- it might get wrapped up into some other File Upload Kit work soon, but if this doesn't block any work, we may not end up prioritizing fixing this.

**Comment by stevelandwehr** [comment]
> @stevelandwehr Hi Steve! I spoke with Kevin last week and it sounded like this does not block work for BoP; is that correct? I'm going to add this to our backlog in Runway-- it might get wrapped up into some other File Upload Kit work soon, but if this doesn't block any work, we may not end up prioritizing fixing this.

Hi Samantha. No, this is not currently blocking anything for BoP.

**Comment by samantharogersphrg** [comment]
This is now tracked in Runway as [NUXE-950](https://nitro.powerhrg.com/runway/backlog_items/NUXE-960).

**Comment by thestephenmarshall** [comment]
Closing as this is now in master
