### ISSUE TITLE
AddOn Variant of Text Input kit does not have full border [NUXE-978]

### ISSUE THREAD

**Issue by web-kat** [powerhome/playbook#1596]
**Describe the bug**

**To Reproduce**
1. Go to TextInput kit on Playbook site
2. Click into the AddOn variant of the kit
3. See the border does not wrap around the whole input
4. The same is true for the error state

**Expected behavior**
The border should wrap around the whole input

**Screenshots**
<img width="666" alt="Screen Shot 2021-08-25 at 2 58 54 PM" src="https://user-images.githubusercontent.com/38359249/130962118-03b405cd-de36-4966-a8ba-a44b9eb38724.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by samantharogersphrg** [comment]
Hi Katie! Just making sure I understand this-- is there a variant in particular that you're expecting to look different? Will "Left-Aligned Add On With Border" work for you?

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/54685365/132517436-27877e8a-3570-49a3-b4d6-307965cf188a.png">

**Comment by web-kat** [comment]
@samantharogersphrg it does work as intended. The issue I was pointing out was that we expected to see the border wrap around the add-on as well (in this example, the % sign). It is feedback I received in an auction story from product/ninjas and I believe @kre8sions suggested we open an issue for it.

**Comment by jasoncypret** [comment]
This shipped to production awhile back. Forgot to close
