### ISSUE TITLE
Performance Issue (Possibly in the Icon Kit)

### ISSUE THREAD

**Issue by gregblake** [powerhome/playbook#1635]
**Describe the bug**

@powerhome/rebel-alliance recently noticed performance issues in the Connect v3 web client. We think it could be related to the Icon kit.

**To Reproduce**

We encountered a performance issue on our local environments, while working on a Connect v3 web client feature. These comments describe the issue in more detail: [comment 1](https://github.com/powerhome/connect-web/pull/82#issuecomment-947745053), [comment 2](https://github.com/powerhome/connect-web/pull/82#issuecomment-948622508).

After troubleshooting the issue, I was able to recreate the slowness with only [this change](https://github.com/powerhome/connect-web/commit/5fc4db40addbb496076d3d7ddae4b10964e46abe). Checking out this branch and testing with/without the changes on 5fc4db40addbb496076d3d7ddae4b10964e46abe is likely the easiest way to reproduce the issue.

The code that introduces the slow down only renders the `<InlineLoading/>` component (which, in turn, [renders](https://github.com/powerhome/playbook/blob/master/playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.jsx#L25-L30) an `<Icon/>`) and the spinner icon from Font Awesome. This change also caused a slow down in the list of the v3 web client that renders an `<Icon/>`.

Shortly after that, @codemonium experienced something similar when adding a new feature to the web client. He added something that renders an `<Icon/>`, and the feature became extremely slow on his local environment. Igor confirmed that the component works perfectly in a brand new create-react-app, and he eventually narrowed it down to the `<Icon/>` component.

We also compared the performance in Chrome and Firefox. The above performance issues are not happening to us when we use Firefox on our local development environments. 

In addition, we have not noticed a slow down in deployed environments.

**Expected behavior**

The same behavior, without a performance hit.

**Screenshots**

Here are screen recordings that @codemonium made:

* [Before](https://user-images.githubusercontent.com/1179668/139715396-0500474c-feaf-4757-ae06-b171f999d8ac.mov
)
* [After](https://user-images.githubusercontent.com/1179668/139715418-7984b10a-78a4-4b24-ad35-ed9f5c597114.mov)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 95.0.4638.54 (Official Build) (x86_64)

**Comment by samanthar8** [comment]
Hi Greg! We might have this tracked in Runway-- do you mind taking a look at [this ticket](https://nitro.powerhrg.com/runway/backlog_items/NUXE-36), and seeing if it lines up with the issue you're seeing?

**Comment by gregblake** [comment]
Hey @samanthar8! Yes, I believe that ticket describes the same issue we've seen.

The only difference is that we notice the performance issue with fewer than 150 icons in a given view (at least on our local development environments).

**Comment by samanthar8** [comment]
Additionally, Jasper told me that "A current workaround that Stephen greer used at one point was to just use an <i> element with fontawesome as declared in their docs", which may not be the same thing referenced in the prior comment?

**Comment by gregblake** [comment]
@samanthar8 Yes, if we made those changes, it would help to speed up Connect. 

But, I believe making the change in Connect would have two downsides:

1. Feature drift: at some point in the future, changes will be made to the `<Icon/>` component in Playbook (e.g. maybe a styling change will be made). Depending on the change, we may also need to make a similar change to Connect.
2. It wouldn't solve the root cause of the performance issue. And, this issue likely effects many parts of our application, to varying degrees of impact. Generally speaking, performance issues like this happen on a sliding scale. If a page only has a *few* icons, the performance impact might not be noticeable to the user. But each additional icon on the view makes the performance *incrementally* slower. Almost every page in Nitro uses the top and left navigation menus, which contain roughly 60 icons (which doesn't include the icons in the main content of any given page). So, I believe making this performance improvement in Playbook would improve page load times on nearly every page in Nitro. In other words, the performance change would be more noticeable on pages with several hundred icons (like Connect v3). But it would also speed up performance on pages that have fewer than 150 icons (just to a lesser degree).

That's why I believe the best solution is to make one of the changes suggested in [NUXE-36](https://nitro.powerhrg.com/runway/backlog_items/NUXE-36) directly in Playbook.

**Comment by co1in-1ewis** [comment]
Closing and moving to [PLAY-850](https://nitro.powerhrg.com/runway/backlog_items/PLAY-850) for follow-up.
