### ISSUE TITLE
Selectable Card Icon Circle

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#165]
https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard33

This should use selectable card kit if built. Otherwise, this should use cards and active state to affect borders. Under the hood these should use either checkboxes or radios as these will be used in forms. See toggle for example implementation. 

Use circle icon, + title + body

![image](https://user-images.githubusercontent.com/863031/64578214-55aabb00-d344-11e9-8430-4a7b1689ce65.png)

**Comment by thestephenmarshall** [comment]
This should be pretty easy based on https://playbook.powerapp.cloud/kits/selectable_card and https://playbook.powerapp.cloud/kits/selectable_card_icon

**Comment by jasoncypret** [comment]
Would be better to build an example
