### ISSUE TITLE
Selectable Card Image

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#166]
Design details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard32

This should use selectable card kit if built. Otherwise, this should use cards and active state to affect borders. Under the hood these should use either checkboxes or radios as these will be used in forms. See toggle for example implementation.

Use image kit, + title

![image](https://user-images.githubusercontent.com/863031/64578314-ad492680-d344-11e9-9009-8197175f2a8c.png)

**Comment by thestephenmarshall** [comment]
This one should be pretty easy based on https://playbook.powerapp.cloud/kits/selectable_card_icon and https://playbook.powerapp.cloud/kits/selectable_card

**Comment by jasoncypret** [comment]
Will build version to show this example
