### ISSUE TITLE
Checkbox Cards

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#169]
Design Details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard29

This kit should use the Card kit. Just use default checkboxes for now, you do not have to do checkbox styling for today. This kit should have a selected and unselected state. When the user selects the checkbox, the card should also become selected. The user should be able to set the kit the be selected by default.

![image](https://user-images.githubusercontent.com/863031/64632027-f2f60580-d3bd-11e9-9e1b-c40ce4903b65.png)

**Comment by jasoncypret** [comment]
Runway support ticket: https://nitro.powerhrg.com/runway/backlog_items/NUX-1395

**Comment by coleerikson** [comment]
Sister ticket: https://github.com/powerhome/playbook/issues/170

**Comment by coleerikson** [comment]
"Could be an option on selectable cards where it just shows the checkbox & radio." Per Jason
