### ISSUE TITLE
Table Kit: Better Support for collapse="lg" 

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#1697]
The table kit currently supports desktop and mobile pretty well, but does not do such a great job with regards to the `collapse="lg"` being applied which attempts to break at 3 points from desktop to ipad to mobile. 

**Describe the solution you'd like**
Apply better support for in between desktop and ipad size. See screenshot below:

<img width="830" alt="Screen Shot 2021-12-16 at 12 26 22 PM" src="https://user-images.githubusercontent.com/2293844/146602398-863b8205-9a48-4590-bc17-8616de43bb07.png">

**Describe alternatives you've considered**
Suggestion is perhaps we can update the CSS to continue scaling from desktop to tablet

**Comment by jasoncypret** [comment]
Closing this request. Discuss at dailies
