### ISSUE TITLE
Inventory Location

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#172]
Design Details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard10

This kit should use the Caption, Icon, Body light and Title kits. The kit should accept a location Type, and the icon should be automatically defined within the kit based on type.  The types should be Rack or Cart.  The location text should have an optional link.

![image](https://user-images.githubusercontent.com/863031/64644063-6c4e2200-d3d7-11e9-811e-3fb109c131ce.png)

# PR: https://github.com/powerhome/playbook/pull/275

**Comment by christinaatai** [comment]
Became part of Logistic Kit
