### ISSUE TITLE
Owner Project

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#175]
Extend label value to be able to stack and reverse the order of the kits so this option is avaliable.
![image](https://user-images.githubusercontent.com/863031/64644205-ba632580-d3d7-11e9-8a38-49a6b61d2cc7.png)

**Comment by jasoncypret** [comment]
@kre8sions can we come up with a more generic name for this that is not Nitro specific.

Home, id, date? The examples can stay project specific

**Comment by christinaatai** [comment]
Need some more clarifications before creating this kit. Should we make this a variation of Logistic Kit?

**Comment by jasoncypret** [comment]
Closing for now. We can add an [icon value](https://playbook.powerapp.cloud/kits/icon_value/react) kit under the label value kit to achieve this
