### ISSUE TITLE
Legend Indicator

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#178]
Design Details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard22

This kit should use the Title and Body light kit for the text, and accept a data color within Playbook tokens.

![image](https://user-images.githubusercontent.com/863031/64826280-28514d80-d58e-11e9-8ee3-266a30bf1b6d.png)

**Comment by thestephenmarshall** [comment]
PR: https://github.com/powerhome/playbook/pull/549
