### ISSUE TITLE
Timeline Details

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#189]
Design Details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard9

This kit should use the Title Detail kit, and the Icon Circle kit. This kit should have both a vertical and horizontal orientation. This kit should also accept an option for a solid or dashed line.

![image](https://user-images.githubusercontent.com/863031/64827285-96e3da80-d591-11e9-89c3-71431d69de5f.png)

These 2 should be built with this kit...probably the same kit
![image](https://user-images.githubusercontent.com/863031/63182893-9f440680-c021-11e9-8d6d-52d91d61e1f0.png)

Design Details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard39

This should use icon circle.

![image](https://user-images.githubusercontent.com/863031/64826705-85013800-d58f-11e9-8191-cf8f8840d392.png)

**Comment by jasoncypret** [comment]
Good example: https://codepen.io/2ne/pen/pHvaf

**Comment by jasoncypret** [comment]
![image](https://user-images.githubusercontent.com/863031/78297939-4ebce300-74f6-11ea-88d3-864fd41ec567.png)

**Comment by jasoncypret** [comment]
Linked: [NUX-899](https://nitro.powerhrg.com/runway/backlog_items/NUX-899)

**Comment by christinaatai** [comment]
Done in this PR: https://github.com/powerhome/playbook/pull/839
