### ISSUE TITLE
React: DatePicker kit expects a page reload

### ISSUE THREAD

**Issue by haydenrou** [powerhome/playbook#1908]
Hi team,

I was debugging an issue I came into working on [INC-953](https://nitro.powerhrg.com/runway/backlog_items/INC-953). Using the React Filter kit and DatePicker inside of it, I found that when selecting a new date and pressing apply, the value of the DatePicker would turn blank. If I closed the popover and re-opened it, the value was correct.

After debugging this with @jasperfurniss and @thestephenmarshall we were able to determine that when copied from the Rails to newer React kit, the Filter kit expects a full reload to load these values as it usually would with Rails - however in React there is no page-reload. There aren't any usable hooks from the API that I can use to get around this.

My workaround for the moment is that we are closing the modal when pressing Apply - which in all honestly is a nice UX decision anyway, but the bug still stands, it's just not as high priority for us anymore.

The area of code this concerns lives in [this PR](https://github.com/powerhome/nitro-web/pull/25577/files#diff-806fa3b29eed7bc358c4c580b49a45a533f6d26851d06e48afe3d90009b6522eR25-R35). To reproduce you can go to localhost:3000/sales/adoption_dashboard/reps and remove [the code that closes the popover](https://github.com/powerhome/nitro-web/pull/25577/files#diff-72a420c69fa5d2a6fde599640a8bdcedc7a6cb59c5cbc9b643f42d37c8b60a95R37).

**Expected behavior**
I'd expect the value to change when pressing apply. (in the scenario that from a UX perspective they wanted the popover to stay open, and maybe the apply button to turn into a spinner)

**Screenshots**
https://user-images.githubusercontent.com/21108297/169035542-5833b158-f4a2-4e04-915f-0d3627ce345e.mov

**Comment by co1in-1ewis** [comment]
@haydenrou a fix for this issue now in progress in [PLAY-365](https://nitro.powerhrg.com/runway/backlog_items/PLAY-365). You are already tagged as a reviewer on that story for reference, and I'm closing this issue here.
