### ISSUE TITLE
Home ID in HomeAddressStreet should open in a new tab

### ISSUE THREAD

**Issue by gerald** [powerhome/playbook#1997]
**Is your feature request related to a problem? Please describe.**
It has been brought up that when our warranty service users work they want their links to open in a new tab so they can keep their main dashboard open in a tab and look at home information in the other tabs.

**Describe the solution you'd like**
Add a prop to indicate whether a link should open in a new tab.

**Describe alternatives you've considered**
The workaround I implemented was to not display the home id from the `HomeAddressStreet` component. I then created a new link that displays the same data but the link opens in a new tab.

Relevant PR: https://github.com/powerhome/nitro-web/pull/26722/files

**Comment by jasperfurniss** [comment]
Let's track this in runway now: https://nitro.powerhrg.com/runway/backlog_items/PLAY-277 @gerald
