### ISSUE TITLE
Date Picker Dropdown Placement Prop

### ISSUE THREAD

**Issue by dmcindoe** [powerhome/playbook#2004]
**Is your feature request related to a problem? Please describe.**
Currently Date Picker only drops down the calendar to select dates directly below input. Only way to adjust dropdown currently is with a lot of custom CSS. 

**Describe the solution you'd like**
Add in a prop to the Date picker Kit that will allow for adjustment the placement of the drop down. 

**Additional context**
Flatpickr already has config options set within it to adjust how the calendar renders. Using the "position" config the dropdown can be positioned using a string. "[vertical] [horizontal]"  Vertical can be auto, above or below (required). Horizontal can be left, center or right. e.g. "above center"

**Comment by jasperfurniss** [comment]
Let's track this now in Runway: https://nitro.powerhrg.com/runway/backlog_items/PLAY-274
