### ISSUE TITLE
Time Stacked

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#204]
Design details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard4

Use existing kits to build text. This should take a time object and convert it to display.

![image](https://user-images.githubusercontent.com/863031/65063088-1f240000-d943-11e9-867a-c3d4cc891e93.png)

**Comment by haydenrou** [comment]
Live here https://playbook.powerapp.cloud/kits/time_stacked/react
