### ISSUE TITLE
Hashtag

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#208]
Design details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard43

This kit should add the `P#` for projects, `H#` for homes, and `#` for general hashtags. These should also be clickable.

See Nitro Hashtags for other references: https://wiki.powerhrg.com/Nitro-Hashtags

![image](https://user-images.githubusercontent.com/863031/65074158-d9befd00-d959-11e9-80a5-6c2ef2af8dce.png)

**Comment by bklang** [comment]
Is there a place to either embed or link to the Hashtag usage docs? They are currently found in the Wiki

**Comment by jasoncypret** [comment]
@bklang I added a link to the wiki. Some of the ones listed don't seem to be in use.
