### ISSUE TITLE
Range Slider

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#211]
Design details: https://tech.powerhrg.com/playgrounds/sketch_measure/new_kits/#artboard0

![image](https://user-images.githubusercontent.com/863031/65074944-8188fa80-d95b-11e9-87f8-20925e9a5078.png)

Some references to achieve this look with CSS only:
https://codepen.io/noahblon/pen/OyajvN
https://codepen.io/lauraalpinto/pen/jJPZXP
https://codepen.io/brandonmcconnell/pen/oJBVQW

**Comment by jasoncypret** [comment]
So after looking at this further we have 2 different options.

1) change the design so we don't need to add all those shadows.
2) go with a javascript solution. I found several but we need a way to make this work for rails and react

**Comment by drborges** [comment]
@jasoncypret both options sound reasonable to me.

> 1. change the design so we don't need to add all those shadows.

Would you have an alternate design that could also work? I was playing around with the CSS last night and came up with this:

![2019-09-25 10 45 34](https://user-images.githubusercontent.com/508128/65614242-4acb6980-df85-11e9-9353-1f3ab06fe6bd.gif)

Thoughts?

> 2. go with a javascript solution. I found several but we need a way to make this work for rails and react

If the current design is what's desirable, I can surely spend some time this week getting the JS version working, the only downside I see here is the potential JS logic duplication between the Rails and React versions.

**Comment by jasoncypret** [comment]
I’m leaning towards a JS solution after playing with a couple of them. Perhaps a vanilla JS range plugin would work well with rails and react. The other thought would be experiment with a react first solution and having the rails version just render the react component in a rails-y way.
