### ISSUE TITLE
React: Tooltip kit does not accept flex options

### ISSUE THREAD

**Issue by sergiopvilar** [powerhome/playbook#2212]
#### Expected behavior
Tooltip kit should accept Flex options such as `flexDirection`, `flexWrap`, `flexGap`, `alignItems`, `justifyContent`, `flex`, `flexGrow` and `flexShrink`.

#### Describe the bug
Tooltip kit has a Flex but does receive the props to allow us to manage manage how the content is displayed in that flex.

#### Code Sandbox Link with the Bug
https://codesandbox.io/s/stoic-easley-iezv9t?file=/src/App.js

#### Video or Gif

![Dec-13-2022 16-43-46](https://user-images.githubusercontent.com/860636/207430258-44eee7fc-49e4-4ff1-9bd0-d2ecf0b6140e.gif)

#### Screenshots
Please include at least one screenshot demonstrating your bug. 

#### Medium:
  A follow-up history will be adopted to implement the changes on our side once this gets fixed. We have a project to deliver on december 22 that relies on this bug fix.

#### Steps to reproduce the behavior:

Setup a Tooltip that receives a JSX component on the `text` prop. The JSX component has a list of `FlexItem`. Try to align the `FlexItems` using `flexDirection` props specified on the kit's docummentation.

## 📎 Additional context

[Flex implementation on Tooltip kit](https://github.com/powerhome/playbook/blob/master/playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx#L118)

**Comment by evalouderback** [comment]
<img width="754" alt="Screen Shot 2022-12-13 at 3 20 40 PM" src="https://user-images.githubusercontent.com/50629488/207435737-65c42dd6-cba6-4c85-9ea7-1f70acf0cbc3.png">
For reference, we would like to be able to do this ^ with the tooltip
