### ISSUE TITLE
[Rails] Allow Selectable Card Icon kit to accept a custom icon

### ISSUE THREAD

**Issue by haydenrou** [powerhome/playbook#2471]
**Is your feature request related to a problem? Please describe.**
The `SelectableCardIcon` kit for React allows you to pass in a `customIcon` and will pass this prop down to the `Icon` kit, however the rails version of this kit does not do that.

**Describe the solution you'd like**
I'd like to be able to provide the SelectableCardIcon kit a custom icon

**Describe alternatives you've considered**
Changing the page to react?

**Additional context**

**Comment by co1in-1ewis** [comment]
Thanks @haydenrou! I'm closing this issue in favor of [PLAY-779](https://nitro.powerhrg.com/runway/backlog_items/PLAY-779)
