### ISSUE TITLE
List Kit needs to use true value for props

### ISSUE THREAD

**Issue by kre8sions** [powerhome/playbook#253]
You need to specify borderless:false to enable borders. We want borders enabled by default.

<a href="https://cl.ly/22b2eb9c391b" target="_blank"><img src="https://d36przsyicg9u7.cloudfront.net/items/2b40151F1K3N3x3U360l/Screen%20Shot%202019-09-20%20at%201.08.39%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by garettarrowood** [comment]
This kit has since been refactored into the new Ruby syntax and "_borderless" implementation is fixed.
