### ISSUE TITLE
Link kit

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#257]
This could be a kit or not. Needs some discussion before starting. We will add links around kits. Some of these should have the color of the text to blue to let the user know it's clickable.

**Comment by jasoncypret** [comment]
We need all of our typography patterns to be optionally links. Perhaps hover and all

**Comment by thestephenmarshall** [comment]
The design for this one can be taken from https://playbook.powerapp.cloud/kits/button/rails with the exception for spacing, which will need to be adjusted to the normal spacing found by the default stylesheet.

**Comment by jasoncypret** [comment]
Feels like a link utility?
