### ISSUE TITLE
Making SASS changes too quick kills the transpiler

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#263]
Causes the transpiler to stop responding and there is no output. 

***Steps to Reproduce***

1. Make a change to SASS file
2. make another change to the same SASS file immediately before the previous change compiles

**Comment by thestephenmarshall** [comment]
Resources have been drastically reduced. Please re-test with the latest version and let's close this if not reproducible.

**Comment by jasoncypret** [comment]
I believe this is no longer an issue. Closing for now
