### ISSUE TITLE
Fix telemetry links in the Milano UI

### ISSUE THREAD

**Issue by indiebrain** [powerhome/playbook#2762]
**Describe the bug**

The links to the staging and production Metrics dashboards and logs are broken in the Milano Stack UI. 

**To Reproduce**

Staging:

1. Visit https://milano.powerapp.cloud/powerhome/playbook/staging
2. Click on "More"
3. Click on "Metrics"
4. Observe that the linked dashboard does not exist. 

1. Visit https://milano.powerapp.cloud/powerhome/playbook/staging
2. Click on "More"
3. Click on "Logs"
4. Observe that there are no logs

Production:
1. Visit https://milano.powerapp.cloud/powerhome/playbook/production
2. Click on "More"
3. Click on "Metrics"
4. Observe that the linked dashboard does not exist. 

1. Visit https://milano.powerapp.cloud/powerhome/playbook/production
2. Click on "More"
3. Click on "Logs"
4. Observe that there are no logs

**Expected behavior**

The browser should navigate to Playbook's actual metrics dashboards and logging infrastructure:

- [Staging Metrics](https://metrics.powerapp.cloud/d/s9c8D_K7k/pod-resource-usage?orgId=1&refresh=10s&var-datasource=prometheus-app-beta-hq&var-namespace=playbook-staging&var-filter=.%2B&var-pod=All)
- [Staging Logs](https://logging.beta.hq.powerapp.cloud/app/kibana#/discover?_g=h@44136fa&_a=h@8773203)
- [Production Metrics](https://metrics.powerapp.cloud/d/s9c8D_K7k/pod-resource-usage?orgId=1&refresh=10s&var-datasource=prometheus-app-prod-hq&var-namespace=playbook-production&var-filter=.%2B&var-pod=All)
- [Production Logs](https://logging.prod.hq.powerapp.cloud/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c18d3bb0-80c3-11ed-928d-67e2505d2bc3,key:kubernetes.namespace_name,negate:!f,params:(query:playbook-production,type:phrase),type:phrase,value:playbook-production),query:(match:(kubernetes.namespace_name:(query:playbook-production,type:phrase))))),index:c18d3bb0-80c3-11ed-928d-67e2505d2bc3,interval:auto,query:(language:lucene,query:''),sort:!(time,desc)))

**Comment by co1in-1ewis** [comment]
closing this in favor of [PLAY-1108](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1108).
