### ISSUE TITLE
TextInput addOn does not work when passing a child/custom input field 

### ISSUE THREAD

**Issue by drborges** [powerhome/playbook#2925]
**Describe the bug**

Passing a custom `input` element as a child of `TextInput` causes the `addOn` prop to not work.

**To Reproduce**

The following does not render the `addOn`:

```tsx
<TextInput addOn={{ icon: "user", alignment: "left", border: true }}>
  <input />
</TextInput>
```

The following does:

```tsx
<TextInput addOn={{ icon: "user", alignment: "left", border: true }} />
```

[Here's a codesandbox](https://codesandbox.io/p/sandbox/playbook-spikes-55rhpp?file=%2Fsrc%2Findex.tsx%3A18%2C42) that can be used to reproduce the problem.

**Expected behavior**

The `addOn` should be rendered even if a child `input` element is passed to `TextInput`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version latest Playbook version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by co1in-1ewis** [comment]
closing this issue in favor of [PLAY-1237](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1237)
