### ISSUE TITLE
playbook_ui minor patch from 13.22.0 => 13.23.0 breaks semantic versioning and is not a valid upgrade path on Rails 7.1

### ISSUE THREAD

**Issue by indiebrain** [powerhome/playbook#3325]
**Describe the bug**
The playbook_ui minor patch from `13.22.0` => `13.23.0` [breaks semantic versioning](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) Playbook is [no longer installable on my Rails 7.1](https://github.com/powerhome/example-rails-app/pull/423). These semantics changed in [this PR](https://github.com/powerhome/playbook/commit/4d179c672c8fc554a235c34246f1a0dde40ea622#diff-14c9f8391ff13e0125d9abf5439cee7e259fc8da50d8a4ceba7e68ce66aeff03R34-R36).  See [the Semantic Versioning guides](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backward-incompatible-change-as-a-minor-version) offer a resolution path for accidentally releasing non-backward compatible changes in a minor patch.

Is support for Rails 7.1 on the roadmap? Any idea how long we'll need to wait in order to upgrade?

**To Reproduce**
1. In a rails 7.1 app, add playbook_ui 13.22.0 as a dependency
2. Change the playbook_ui version to 13.23.0 an attempt to update the dependency
3. Observe:
```
etching gem metadata from https://rubygems.org/........
Resolving dependencies...

Could not find compatible versions

Because playbook_ui >= 13.23.0 depends on activesupport >= 5.2.4.5, <= 7.0.8.1
  and rails >= 7.1.3.2 depends on activesupport = 7.1.3.2,
  playbook_ui >= 13.23.0 is incompatible with rails >= 7.1.3.2.
So, because Gemfile depends on rails = 7.1.3.2
  and Gemfile depends on playbook_ui = 13.23.0,
  version solving has failed.

```

**Expected behavior**

Minor version upgrades shouldn't require manual intervention

**Comment by co1in-1ewis** [comment]
closing this issue in favor of [PLAY-1298](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1298)
