### ISSUE TITLE
Update Avatar kit to protect against broken images

### ISSUE THREAD

**Issue by markiearnold** [powerhome/playbook#351]
Update Avatar kit to use `<object>` rather than `<img>`

By using object tag, content within tag will be shown instead, if image is broken.

---

Example for top left avatar in Nitro:
```html
<object class="profile-avatar" data="https://my-avatar-image.jpg" type="image/jpg">
    <span>MA</span>
</object>
```

---

Example of broken image in demo environment:
![](https://d2y84jyh761mlc.cloudfront.net/items/2B3I2g0k3W162B2i302X/Image%202019-10-11%20at%202.28.21%20PM.png?X-CloudApp-Visitor-Id=3221729)

**Comment by jasoncypret** [comment]
Linked: [NUX-1021](https://nitro.powerhrg.com/runway/backlog_items/NUX-1021)
