### ISSUE TITLE
Playbook causes consumer applications' test suites to depend on Wikipedia

### ISSUE THREAD

**Issue by benlangfeld** [powerhome/playbook#3584]
**Describe the bug**
```
DevDocs::PlaybookController GET #index loads

     Failure/Error: <%= pb_kits(type: "rails")%>

     

     ActionView::Template::Error:

       Failed to open TCP connection to upload.wikimedia.org:443 (execution expired)
```

**To Reproduce**
https://ci.powerapp.cloud/job/powerhome/job/nitro-web/job/master/10801/display/redirect

**Expected behavior**
It should not be necessary to connect to Wikipedia to render pages.

**Additional context**
https://github.com/search?q=repo%3Apowerhome%2Fplaybook%20upload.wikimedia.org&type=code

**Comment by co1in-1ewis** [comment]
closing this issue in favor of [PLAY-1519](https://runway.powerhrg.com/backlog_items/PLAY-1519)
