### ISSUE TITLE
Range Slider Kit

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#397]
React Only to start!
![image](https://user-images.githubusercontent.com/863031/90434641-60f98100-e093-11ea-9bf1-1a6f996a9a70.png)

This is a good library if you want to use. Whatever is used should be able to be placed within a form.
https://refreshless.com/nouislider/

[Original PR](https://github.com/powerhome/playbook/pull/276)

**Comment by jasoncypret** [comment]
I found this library. It seems to work really well and be styled pretty easily.

https://demos.creative-tim.com/blk-design-system/docs/1.0/plugins/sliders.html
https://refreshless.com/nouislider/

**Comment by jasoncypret** [comment]
Original story: #211

**Comment by jasoncypret** [comment]
Runway support story: https://nitro.powerhrg.com/runway/backlog_items/NUX-1398

**Comment by thestephenmarshall** [comment]
Another idea https://whoisandy.github.io/react-rangeslider/
