### ISSUE TITLE
Node version 8.9.4 does not work

### ISSUE THREAD

**Issue by rafbgarcia** [powerhome/playbook#475]
Package.json file says node version can be `"node": "8.9.4 || 10.17.0",` but v8.9.4 errors with:

```
➜  playbook git:(master) yarn
yarn install v1.13.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error eslint@6.6.0: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "8.9.4"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

`v10.17.0` works just fine.

**Comment by thestephenmarshall** [comment]
Yep, `8.9.4` is going to be dropped 100% [this month](https://cl.ly/2cd8845a154b)

https://nodejs.org/en/about/releases/

The `.nvmrc` is set to use `10.17.0` 

FWIW I've also mentioned this to the dev team and beyond in Connect.

**Comment by thestephenmarshall** [comment]
[Runway #472](https://nitro.powerhrg.com/runway/backlog_items/NUX-462)
