### ISSUE TITLE
Enable ESLint Completely

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#483]
This PR was opened recently: https://github.com/powerhome/playbook/pull/482 which would enable ESLint for all of Playbook. ESLint would run during builds and provide helpful insight into warnings and errors on top of what has already been enabled in overcommit.yml for commits. 

As mentioned in the PR comments, we should phase this rollout and likely do the same for Huddle as well. Thanks to @rafbgarcia for kicking this off!

**Comment by rafbgarcia** [comment]
Milestone

- [ ] **STEP 1** Create a PR that updates only the config changes .eslintrc.json, ect and do not make it retroactive #484
- [ ] **STEP 2** Fix the non-kit JS warnings and errors with the above ^ #484
- [ ] **STEP 3** Incrementally update each kit (or perhaps groups of kits) to remove lint errors and warnings - commits should be kit focused, so one commit per kit. While these changes are only fixing lint errors, we all know that if even the slightest possibility exists for a chance to break a kit then we want to be able to at least track the change down quickly. Breaking this out into kits allows for that.

**Comment by gmfvpereira** [comment]
I think it should be safe to have a `STEP 2.1` PR where we change all occurrences that are "auto fixed" by eslint. Do you see any drawbacks to this approach?

**Comment by rafbgarcia** [comment]
@gmfvpereira https://github.com/powerhome/playbook/pull/484 does that for all non-kit files.

**Comment by gmfvpereira** [comment]
What's the problem with doing the auto fix even for the kits?

**Comment by rafbgarcia** [comment]
The only issue I see is possible conflicts with the PRs currently opened. Maybe @thestephenmarshall has other concerns.
