### ISSUE TITLE
Select Kit Arrow is not Clickable

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#545]
It appears as though an SVG was used from FontAwesome as an HTML element alongside the select itself. Likely, what we will want to do is try to attempt getting `select:after` working for this kit so that the arrow down is also active.

<img width="526" alt="screen-shot-2020-01-03-at-11-54-30-am" src="https://user-images.githubusercontent.com/2293844/71737950-c22d5680-2e1a-11ea-8ee2-3dfa5b506fed.png">

**Comment by jasoncypret** [comment]
Fixed in latest release!
