### ISSUE TITLE
Expanded tables

### ISSUE THREAD

**Issue by jasoncypret** [powerhome/playbook#562]
##### Kit Background & Use Cases
Developers are using expanded table patterns more and more. We need a global solution and possible table kits made available to achieve this. _Can the collapsable kit be used inside the table kit?_

##### Screens & Design References
![image](https://user-images.githubusercontent.com/863031/93363834-68848500-f80d-11ea-9c5c-59ec88e18120.png)
https://huddle.powerapp.cloud/projects/124/handoffs/243

##### Kit Specifications 
The kit should allow a user to place a trigger on an element in a table that will expand an area below the table. Tables are tricky so the row that expands will need to handle its own columns or in some cases won't be another table at all. This might cause the table kit to create two new sub kits that can be used for these cases (trigger, and expanded content). The popover kit's structure might be a good reference. **THIS KIT WILL REQUIRE JS**

##### Example Props
- Trigger should be a direction icon that swaps to up when open.  
- TBD based on implementation.

**Comment by jasoncypret** [comment]
Linked: [NUX-1016](https://nitro.powerhrg.com/runway/backlog_items/NUX-1016)

**Comment by jasoncypret** [comment]
@kre8sions Would we be able to use the collapsable kit in a table?

**Comment by kre8sions** [comment]
You can use it in a table but it wouldn't behave like you would expect it to. It would not open the table up / create a row on the table. It would expand just the cell that the collapse kit lives in
