### ISSUE TITLE
Create more comprehensive kit spec test in Nitro Web

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#612]
Right now our spec test is really a joke. We need to be able to assure that all of our kits are loading, potentially using a dynamically built comment tag in the HTML output.

**Comment by jasoncypret** [comment]
Linked: [NUX-1022](https://nitro.powerhrg.com/runway/backlog_items/NUX-1022)

**Comment by jasoncypret** [comment]
Closing in leu of runway 1022 ^^^. Needs more discussion
