### ISSUE TITLE
Date Range Inline (kit update)

### ISSUE THREAD

**Issue by christinaatai** [powerhome/playbook#613]
First search through Nitro where date range inline is used to confirm that this change does not affect the UI negatively.

Props:
- Icon
- Dark
- Alignment
- Size

Things to note: 
- Year should only show if it is not the current year (i.e. if the date range is 1/1/19 to 1/3/19, the text should say "Jan 1, 2019 → Jan 3, 2019")
- Space between icon and date range is 4px
- Calendar icon name is `calendar-alt`
- Arrow icon name is `long-arrow-right`
- Icons use body light

![Date Range Inline](https://user-images.githubusercontent.com/42459486/88557693-8ba66b80-cff8-11ea-9512-a71b19860efa.png)

**Comment by jasoncypret** [comment]
Linked: [NUX-636](https://nitro.powerhrg.com/runway/backlog_items/NUX-636)
