### ISSUE TITLE
Date (kit update)

### ISSUE THREAD

**Issue by christinaatai** [powerhome/playbook#615]
First search through Nitro where date is used to confirm that this change does not affect the UI negatively.

Props:
- Show day
- Dark (boolean)
- Alignment (left, center, right)

Things to note:
- Month and day should be abbreviated to the first three letters
- Space on either sides of the dot is 4px
- Style of dot is body, light
- Show year if it is not the current year (i.e. if the date is 1/1/2019, show "Jan 1, 2019")

<img width="615" alt="Screen Shot 2020-02-17 at 1 05 21 PM" src="https://user-images.githubusercontent.com/42459486/74677392-2bc4b280-5186-11ea-9210-95bfaaf694e6.png">

**Comment by jasoncypret** [comment]
Linked: [NUX-638](https://nitro.powerhrg.com/runway/backlog_items/NUX-638)
