### ISSUE TITLE
Time (kit update)

### ISSUE THREAD

**Issue by christinaatai** [powerhome/playbook#616]
First search through Nitro where time is used to confirm that this change does not affect the UI negatively.

Props:
- Show icon (boolean)
- Show time zone (boolean)
- Dark (boolean)
- Alignment (left, center, right)
- Size

Things to note:
- Space between icon, time, and time zone is 4px
- Style and color of time zone and clock icon for default size is body light

![Time](https://user-images.githubusercontent.com/42459486/88558461-8eee2700-cff9-11ea-9f29-9038ea368abb.png)

**Comment by jasoncypret** [comment]
Linked: [NUX-639](https://nitro.powerhrg.com/runway/backlog_items/NUX-639)
