### ISSUE TITLE
Date Time

### ISSUE THREAD

**Issue by christinaatai** [powerhome/playbook#617]
This kit uses [Date Kit](https://github.com/powerhome/playbook/issues/615) and [Time Kit](https://github.com/powerhome/playbook/issues/616).

Props: 
- Day
- Icon
- Orientation

Things to note:
- Time zone is always shown
- Make sure that the year is displayed if it is not the current year. This should be built out in the Date Kit.

![Date Time](https://user-images.githubusercontent.com/42459486/88558626-cb218780-cff9-11ea-90c6-e18fd2708f80.png)

**Comment by jasoncypret** [comment]
Linked: [NUX-640](https://nitro.powerhrg.com/runway/backlog_items/NUX-640)
