### ISSUE TITLE
Timestamp (kit update)

### ISSUE THREAD

**Issue by christinaatai** [powerhome/playbook#618]
This kit uses Caption Kit, size xs.

Props:
- Show date (boolean, default boolean is true)
- Dark (boolean)
- Alignment (left, center, right)

Things to note:
- Default kit includes both time and day
- Year is displayed if it is not the current year
- Space between date, dot, and time is 4px

<img width="880" alt="Screen Shot 2020-02-17 at 1 16 45 PM" src="https://user-images.githubusercontent.com/42459486/74678037-d7bacd80-5187-11ea-9dd1-819809c5e55c.png">

Add Update stamp
Props:
- Show user
- Dark (boolean)
- Alignment (left, center, right)

Things to note:
- Have a custom variant
- Keep a time ago variant (updated 2 days ago) Built into rails and JS has libraries to perform this calculation.

<img width="929" alt="Screen Shot 2020-02-17 at 1 17 10 PM" src="https://user-images.githubusercontent.com/42459486/74678024-d2f61980-5187-11ea-9993-e29d8b5769ab.png">

**Comment by jasoncypret** [comment]
linked [NUX-641](https://nitro.powerhrg.com/runway/backlog_items/NUX-641)

**Comment by jasoncypret** [comment]
@evalouderback I think we made some changes in the sketch kit. I think this is missing "time ago" functionality?
