### ISSUE TITLE
Button Kit raises an error when loading prop changes from true to false

### ISSUE THREAD

**Issue by casadei** [powerhome/playbook#755]
I've found an issue related to the `loading` property of the `Button` kit (React version). Whenever we change the `loading` value from `false` to `true` it acts as expected displaying the icon instead of the text. However, when we do the opposite changing its value from `true` to `false` it raises an error like this:

![image](https://user-images.githubusercontent.com/938522/80264596-06af5d00-866b-11ea-8bf2-8ce6d52470e9.png)

This error can be easily simulated with the following code:

```
import React, { useState } from 'react'
import { Button } from '../../'

const ButtonLoading = () => {
  const [ isLoading, setIsLoading ] = useState(false)

  const handleClick= () => {
    setIsLoading(true)
    setTimeout(() => { setIsLoading(false) }, 5000)
  }

  return (
    <div>
      <Button
          loading={isLoading}
          text="Dynamic Loading"
          onClick={handleClick}
      />
    </div>
  )
}


export default ButtonLoading
```

After investigating the issue, I've figured out that it's being caused by this [block of code](https://github.com/powerhome/playbook/blob/v4.13.0/app/pb_kits/playbook/pb_button/_button.jsx#L85). Behind the scenes, the `FontAwesome` transforms this `<i>` tag into a `<svg>` as documented [here](https://stackoverflow.com/questions/48358529/failed-to-execute-removechild-on-node-with-fontawesome-in-react). Thus, when loading "finishes", React tries to remove that `<i>` tag but it doesn't exist anymore, raising that error. 

It can be easily fixed by wrapping up the `<i>` tag with another like `<div>` or `<span>`. However, there are other approaches to solve that and I'd like to hear other contributors before submitting a PR.

**Comment by thestephenmarshall** [comment]
Thanks for opening this one @casadei

**Comment by gmfvpereira** [comment]
Is anyone working on this one? If not, I'll try to find some time to deal with it.

**Comment by jasoncypret** [comment]
Fixed and released
