### ISSUE TITLE
Currency kit has performance issues in Nitro development

### ISSUE THREAD

**Issue by haydenrou** [powerhome/playbook#797]
Example pages: Solar Roofing landing page estimates. To get to this, go to your console and run

```
token = SolarRoofing::EstimateToken.create(project: SolarRoofing::Project.last, email: SolarRoofing::Project.last.home.emails.last)
token.secure_url
```

This will give you a link like the below
127.0.0.1:5000/solar_roofing/project_portal/eSLWNrSh7sN56uj-ozrP/free_estimates

With a bit of debugging with Stephen, I believe this is the currency kit, which because it's used many times here, is causing a long lag when loading the page.

Here it seems to take 6 seconds:
<img width="424" alt="Screenshot 2020-05-20 at 10 42 16 AM" src="https://user-images.githubusercontent.com/21108297/82459992-9daedf80-9a86-11ea-87d3-abb6262a7cc2.png">

It was mentioned that this could be because there are several renders being ran. Below are some useful links

https://github.com/powerhome/playbook/blob/0f0a824a356fd345c01793dd65dcf78b2d931723/app/pb_kits/playbook/pb_currency/currency.rb
https://github.com/powerhome/nitro-web/blob/master/components/solar_roofing/app/views/solar_roofing/project_portal/free_estimates/_credits.html.erb

@thestephenmarshall I'm happy to pair on this when you get around to it. However, for the time being I'll replace them with pure html to stop it blocking our current work.

**Comment by todtb** [comment]
It could be this: `ApplicationController.renderer.render`. It looks like this functionality has to build up an entirely separate (virtual) rack environment for each call

vendor/bundle/ruby/2.5.0/gems/playbook_ui-4.11.0/app/pb_kits/playbook/pb_currency/currency.rb:45 , 54, 69
Since it's cascading partials it gets called a lot I imagine.

Some benchmarking:
10 calls: 

```ruby
Benchmark.bm do |x|
  x.report { 10.times do
          ApplicationController.renderer.render(
              partial: pb_dollar_sign,
              as: :object
          )
  end}
end
```

```bash
user     system      total        real
0.955457   1.121207   2.076664 (  2.096586)
=> [#<Benchmark::Tms:0x00007ffc67a1edf0 @label="", @real=2.0965860000578687, @cstime=0.0, @cutime=0.0, @stime=1.1212070000000018, @utime=0.9554569999999991, @total=2.076664000000001>]
```

**Comment by thestephenmarshall** [comment]
@todtb correct. This was my assumption a week ago and I have proven it to be true now. PR in progress. Same idea with `body` kit for highlighting.
