### ISSUE TITLE
Body kit should not call render

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#821]
Similar to the information in https://github.com/powerhome/playbook/issues/797, the `body` kit should not be calling `ApplicationController.renderer.render`. This can cause major performance issues.

https://github.com/powerhome/playbook/blob/master/app/pb_kits/playbook/pb_body/body.rb#L40

**Comment by jasoncypret** [comment]
Linked [NUX-1015](https://nitro.powerhrg.com/runway/backlog_items/NUX-1015)

**Comment by jasoncypret** [comment]
Closed in leu of runway since this is UX reported
