### ISSUE TITLE
Officially Enable Webpack Hot Module Replacement Feature in Playbook

### ISSUE THREAD

**Issue by thestephenmarshall** [powerhome/playbook#826]
Currently, [HMR](https://webpack.js.org/guides/hot-module-replacement/) in Playbook is not fully enabled. Work in order achieve this successfully will require configuration and some trial and error. This can be expedited by referring to [this commit in Playgrounds](https://github.com/powerhome/playgrounds/pull/104/commits/82c6a818ebc9006229ba22af0545173a86d8a0a1) which successfully enables HMR. Given that this application runs within the confines of Docker containers, some extra bits will likely need to be added.

**Comment by jasoncypret** [comment]
Related? https://github.com/powerhome/playbook/issues/268

**Comment by jasoncypret** [comment]
Linked [NUX-1014](https://nitro.powerhrg.com/runway/backlog_items/NUX-1014)
