### ISSUE TITLE
Card.Body does not reflect Card spacing props

### ISSUE THREAD

**Issue by gmfvpereira** [powerhome/playbook#856]
When using the new `spacing` feature, my padding choice is not reflected to the `Card.Body`

With this code
```
<PbReactPopover
    closeOnClick="outside"
    offset
    padding="xs"
    placement="bottom"
    reference={actionPopoverTrigger}
    shouldClosePopover={handleShouldCloseActionPopover}
    show={showActions}
>
```

I was expecting that I had an "xs" padding on the popover as a whole since my spacing is being applied to the `Card` [here](https://github.com/powerhome/playbook/blob/v4.18.0/app/pb_kits/playbook/pb_popover/_popover.jsx#L77).

But the `Card.Body` end up getting the default padding as `md` [here](https://github.com/powerhome/playbook/blob/v4.18.0/app/pb_kits/playbook/pb_card/_card.jsx#L49) because at that point the `props.padding` is not set anymore.

Any ideas on how to deal with that?

A possible solution would be to create some sort of `forwardSpacingProps(props)` function, then we could call like this:
```
<Card
    className={spacing(props)}
    shadow="deeper"
    {...forwardSpacingProps(props)}
>
  {children}
</Card>
```

**Comment by jasoncypret** [comment]
@gmfvpereira I believe this fix is being Ninja Tested now

**Comment by jasoncypret** [comment]
This shipped!
