### ISSUE TITLE
Bug on Icon on NavItem (?)

### ISSUE THREAD

**Issue by gmfvpereira** [powerhome/playbook#878]
I found two scenarios where I think that the `iconRight` on the NavItem is not working as it should. 

1 - The page breaks if we remove an Icon from a NavItem. 
Use case: The Icon should only appear on the active NavItem.
Example:
<img width="276" alt="Screen Shot 2020-06-22 at 11 21 15 AM" src="https://user-images.githubusercontent.com/386460/85298568-a24a2780-b47a-11ea-8fb6-0f32796f1f99.png">

Error: `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

Reproducible with:
```
import React, { useState } from "react"
import { NavItem } from "playbook-ui"

const NavItemBug = () => {
  const [ showIcon, setShowIcon ] = useState(true)

  return (
    <If condition={showIcon}>
      <NavItem
          iconRight="ellipsis-v"
          onClick={() => setShowIcon(!showIcon)}
          text="A nav item"
      />
      <Else />
        <NavItem
            onClick={() => setShowIcon(!showIcon)}
            text="A nav item"
        />
      </If>
  )
}

export default NavItemBug

```

This other usage also raises the same error:
```
<NavItem
  iconRight={showIcon ? "ellipsis-v" : ""}
  onClick={() => setShowIcon(!showIcon)}
  text="A nav item"
/>
```

2 - The icon does not update to a new icon, it remains the same forever:
```
<NavItem
  iconRight={selected ? "angle-down" : "angle-right"}
  onClick={() => setShowIcon(!showIcon)}
  text="A nav item"
/>
```

**Comment by jasoncypret** [comment]
@gmfvpereira Just confirming your planning on fixing (just asked Christina). I don't want overlapping fixes. If so I'll assign to you. Thanks!

**Comment by gmfvpereira** [comment]
We'll fix it! Sorry for the delay on getting back to you @jasoncypret

**Comment by jasoncypret** [comment]
Great work @KatherineMuedas !
