### ISSUE TITLE
Image Kit Variant - Rounded Corners

### ISSUE THREAD

**Issue by kre8sions** [powerhome/playbook#997]
##### Kit Background & Use Cases
This kit is needed to display thumbnails of images. Similar to avatar we need to be able to show square sizes of images. The default of the image kit is no width and height. You will be adding new features to the existing image kit. This will enable us to show thumbnails at various sizes. Use avatar sizes for a guide.

##### Screens & Design References
<img width="550" alt="Screen Shot 2020-08-18 at 8 23 47 AM" src="https://user-images.githubusercontent.com/9784112/90512430-25f75c00-e12c-11ea-8d3e-60d74e986757.png">
<img width="310" alt="Screen Shot 2020-08-18 at 8 25 39 AM" src="https://user-images.githubusercontent.com/9784112/90512625-6c4cbb00-e12c-11ea-955b-f51edd45e723.png">

##### Kit Specifications 
This again should just add a new example "selectable cards with images". It should show 5 images that can be selected. Only one selected at a time.

##### Example Props
- sizes: "none (default) | sm | md |lg....ect"
- rounded: "none (default) | rounded"

Add the prop **border_radius** to apply a border radius to image kit.
The rounded prop should take different border radius token from the design system.

**Comment by jasoncypret** [comment]
Needs screenshot and more details

**Comment by maddiemc01** [comment]
this is the PR branch https://github.com/powerhome/playbook/pull/1176

**Comment by jasoncypret** [comment]
Shipped!
